### ISSUE TITLE
RTKQ with graphql-codegen weird error

### ISSUE THREAD

**Issue by nenadfilipovic** [reduxjs/redux-toolkit#1176]
I am using standard api:

```
const api = createApi({
  baseQuery: graphqlRequestBaseQuery({
    url: '/graphql',
  }),
  endpoints: () => ({}),
});
```

standard store:

```
const store = configureStore({
  reducer: {
    map: mapReducer,
    deviceDetails: deviceDetailsReducer,
    [api.reducerPath]: api.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(api.middleware),
});
```

Classic redux implementation:

```
 <ReduxProvider store={store}>
      <NextAuthProvider session={pageProps.session}>
        <Component {...pageProps} />
      </NextAuthProvider>
 </ReduxProvider>
```

Also I am using graphql-codegen plugin for rtk-query, by @phryneas.

Here is generated endpoint:

```
import * as Types from '../../../graphql/generated/client/typegen';

import { api } from 'src/services/api';
export type CreateDeviceMutationVariables = Types.Exact<{
  allow: Types.Scalars['Int'];
  access: Types.Scalars['Int'];
  name: Types.Scalars['String'];
  metadata?: Types.Maybe<Types.Scalars['Json']>;
  elevation?: Types.Maybe<Types.Scalars['Int']>;
  latitude: Types.Scalars['Float'];
  longitude: Types.Scalars['Float'];
  desciption?: Types.Maybe<Types.Scalars['String']>;
}>;

export type CreateDeviceMutation = { __typename?: 'Mutation' } & Pick<
  Types.Mutation,
  'createDevice'
>;

export const CreateDeviceDocument = `
    mutation createDevice($allow: Int!, $access: Int!, $name: String!, $metadata: Json, $elevation: Int, $latitude: Float!, $longitude: Float!, $desciption: String) {
  createDevice(
    input: {name: $name, allow: $allow, access: $access, latitude: $latitude, metadata: $metadata, elevation: $elevation, longitude: $longitude, description: $desciption}
  )
}
`;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    createDevice: build.mutation<
      CreateDeviceMutation,
      CreateDeviceMutationVariables
    >({
      query: (variables) => ({ document: CreateDeviceDocument, variables }),
    }),
  }),
});

export { injectedRtkApi as api };
export const { useCreateDeviceMutation } = injectedRtkApi;
```

Here is error video: https://webmshare.com/play/BeOB4

If I comment out reducer from store app works again.

**Comment by phryneas** [comment]
This is an error from the relay compiler. You should not need relay in any way for RTK-Q. Could it be that this is still somewhere in a generated graphql file from an earlier experiment and just had not showed up before because that file was not referenced anywhere?

**Comment by nenadfilipovic** [comment]
No I dont have any relay specific code, also I can open graphql playground fine.

**Comment by phryneas** [comment]
You might want to investigate why you have the `relay-compiler` package installed there, because that is crashing in your screen recording and it is not anything that would be invoked at runtime by RTK-Query or any code we generate with the codegen.

**Comment by nenadfilipovic** [comment]
This is whole callstack:

```
Call Stack
eval
node_modules/relay-compiler/lib/core/GraphQLCompilerProfiler.js (192:20)
Object../node_modules/relay-compiler/lib/core/GraphQLCompilerProfiler.js
file:///workspace/.next/static/chunks/pages/_app.js (3812:1)
Object.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
node_modules/relay-compiler/lib/core/CompilerContext.js (13:15)
Object../node_modules/relay-compiler/lib/core/CompilerContext.js
file:///workspace/.next/static/chunks/pages/_app.js (3790:1)
Object.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
webpack-internal:///./node_modules/@graphql-tools/relay-operation-optimizer/index.esm.js (15:97)
Module../node_modules/@graphql-tools/relay-operation-optimizer/index.esm.js
file:///workspace/.next/static/chunks/pages/_app.js (227:1)
Module.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
webpack-internal:///./node_modules/@graphql-codegen/visitor-plugin-common/index.esm.js (73:99)
Module../node_modules/@graphql-codegen/visitor-plugin-common/index.esm.js
file:///workspace/.next/static/chunks/pages/_app.js (205:1)
Module.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
webpack-internal:///./.yalc/@graphql-codegen/typescript-rtk-query/dist/index.esm.js (20:97)
Module../.yalc/@graphql-codegen/typescript-rtk-query/dist/index.esm.js
file:///workspace/.next/static/chunks/pages/_app.js (249:1)
Module.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
webpack-internal:///./src/services/api/api.ts (7:95)
Module../src/services/api/api.ts
file:///workspace/.next/static/chunks/pages/_app.js (304:1)
Module.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
webpack-internal:///./src/services/api/index.ts (5:62)
Module../src/services/api/index.ts
file:///workspace/.next/static/chunks/pages/_app.js (315:1)
Module.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
webpack-internal:///./src/store.ts (6:71)
Module../src/store.ts
file:///workspace/.next/static/chunks/pages/_app.js (326:1)
Module.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
webpack-internal:///./src/pages/_app.tsx (5:64)
Module../src/pages/_app.tsx
file:///workspace/.next/static/chunks/pages/_app.js (293:1)
Module.options.factory
/_next/static/chunks/webpack.js (685:31)
__webpack_require__
file:///workspace/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (348:21)
eval
node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app.tsx! (5:15)
eval
node_modules/next/dist/client/route-loader.js (294:22)
```

**Comment by nenadfilipovic** [comment]
With `fetchBaseQuery` it works flawless:

```
const api = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl,
  }),
  endpoints: () => ({}),
});
```

**Comment by phryneas** [comment]
Hmm, I think I see. Can you try to import the `graphqlRequestBaseQuery` directly from the sources instead of the built package?

**Comment by nenadfilipovic** [comment]
When I copy this:

https://codesandbox.io/s/github/reduxjs/redux-toolkit/tree/example/graphql-codegen/examples/query/react/graphql-codegen?file=/src/app/services/graphqlRequestBaseQuery.ts

to my api file it works.

**Comment by nenadfilipovic** [comment]
All ok now :)

**Comment by phryneas** [comment]
Yup, by now we've released it and for now, the baseQuery is released as it's own package - see the graphql-codegen docs on that :)

**Comment by nenadfilipovic** [comment]
Yea I have checked documentation and there you extracted basequery to npm module that is now giving me this error:

https://webm.red/is4M

@phryneas

**Comment by phryneas** [comment]
That seems to be weird tooling. It complains that https://unpkg.com/browse/@rtk-query/graphql-request-base-query@1.0.3/dist/index.modern.js would not be a module since it uses `require`. But that file does not use `require` if you look at it. So it seems your bundler/transpiler transpiles that file to CJS and then complains that it is not an ESM module, which at that point is pretty obious :thinking: 

I have not had any problem like that with CRA (see https://github.com/reduxjs/redux-toolkit/pull/1152 ) - what kind of setup are you using?

**Comment by nenadfilipovic** [comment]
This is stack trace:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /workspace/node_modules/@rtk-query/graphql-request-base-query/dist/index.modern.js
require() of ES modules is not supported.
require() of /workspace/node_modules/@rtk-query/graphql-request-base-query/dist/index.modern.js from /workspace/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.modern.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /workspace/node_modules/@rtk-query/graphql-request-base-query/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@rtk-query/graphql-request-base-query (/workspace/.next/server/pages/_app.js:136:18)
    at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/services/api/api.ts:8:95)
    at Object../src/services/api/api.ts (/workspace/.next/server/pages/_app.js:66:1)
    at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:33:42) {
  code: 'ERR_REQUIRE_ESM'
}
```
And tsconfig

```
    "strict": true,
    "noEmit": true,
    "allowJs": true,
    "jsx": "preserve",
    "types": ["jest"],
    "target": "ES2020",
    "module": "ESNext",
    "skipLibCheck": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "moduleResolution": "Node",
    "forceConsistentCasingInFileNames": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"]
```

**Comment by phryneas** [comment]
Your bundler (webpack?) decides which of those entry points to use and then seems to decide that it needs to transpile it to another format and **then** complains that it has to be un-transpiled.

So, this is not about a tsconfig.json - are you using CRA or a different setup?

**Comment by nenadfilipovic** [comment]
Nah just usual next.js setup, didn't need to touch anything yet about webpack.

**Comment by phryneas** [comment]
So `next` and not `CRA`. Useful information, since those are completely different. I would assume it's an Next bug then to be honest :/
I can try to take a look at it tomorrow

**Comment by nenadfilipovic** [comment]
I will try now in codesandbox and report, it is not crucial because I can use it without this package but it will be nice to find where problem is.

**Comment by nenadfilipovic** [comment]
Something like this gives me error locally : https://codesandbox.io/s/gallant-rosalind-h5d9v but works here.

**Comment by phryneas** [comment]
Fails for me in the sandbox as well. Generally, as I said: i believe this is a next error. Please report it there. You have a reproduction as well now.

**Comment by nenadfilipovic** [comment]
When I first tried it didn't fail but now with clear cache and cookies it does fail in codesandbox. Ok will report there, thanks for help :)

**Comment by nenadfilipovic** [comment]
@phryneas it seems that with new version of next 11.1.0 it does not give errors anymore
