### ISSUE TITLE
createAsyncThunk doesn't return anything, can't access .fullfilled etc + Typescript issues

### ISSUE THREAD

**Issue by hooksjam** [reduxjs/redux-toolkit#1294]
I've been reading all the docs and I'm just trying to create a simple typescript app with createAsyncThunk and createSlice but I'm finding createAsyncThunk isn't returning anything.

```typescript
// appActions.ts
import {
    createSlice,
    createAsyncThunk,
} from '@reduxjs/toolkit'
import { loadApp } from 'services/appServices'
import { AxiosError } from 'axios'
import { RootState } from 'app/reducer'

export type AppState = {
    initialized: boolean
}

const initialState: AppState = {
    initialized: false,
}

type ValidationErrors = {
    errorMessage: string,
    fieldErrors: Record<string, string>
}

export const load = createAsyncThunk<
    string,
    string,
    { state: RootState, rejectValue: ValidationErrors }
>(
    'app/load',
    async (appID, { rejectWithValue }) => {
        try {
            const response = await loadApp(appID)
            return response.data
        } catch (err) {
            const error: AxiosError<ValidationErrors> = err
            if (!error.response) {
                throw err
            }
            return rejectWithValue(error.response.data)
        }
    },
)

const appSlice = createSlice({
    name: 'app',
    initialState,
    extraReducers: (builder) => {
        builder.addCase(load.fullfilled, (state, action) => {
            // Fails at load.fullilled
        })
    },
})

export default appSlice.reducer

// In another file
import { load } from 'app/appActions'
import useAppDispatch from 'app/hooks'
...
const dispatch = useAppDispatch()
dispatch(load())
```

![image](https://user-images.githubusercontent.com/32071563/125493878-7f4cc69c-ab0f-4144-9f34-fb9d64d1f39b.png)

VSCode/Typescript tells me that the 'load' result is of type 'any', and just debugging shows that the value of load is undefined. So its failing to get the .fullfilled and .rejected properties.

**Main question:** Why might be createAsyncThunk not returning the correct value such that typescript can pick it up and I can pass it into the builder? Thank you

More code
```typescript
// store.ts
import { configureStore } from '@reduxjs/toolkit'
import { logger } from 'redux-logger'
import rootReducer, { RootState } from 'app/reducer'

const preloadedState = {}
export const store = configureStore({
    reducer: rootReducer,
    devTools: process.env.NODE_ENV !== 'production',
    middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(logger),
    preloadedState,
})

export type AppDispatch = typeof store.dispatch
export type AppThunk = ThunkAction<void, RootState, null, Action<string>>
```

```typescript
// reducer.ts
import { combineReducers } from '@reduxjs/toolkit'
import appReducer, { AppState } from 'actions/AppActions'

const rootReducer = combineReducers({
    app: appReducer,
})

// Fix because I couldn't get TS to infer the root state from the ReturnType<typeof rootReducer>
export type RootState = {
    app: AppState
}
export default rootReducer
```

```typescript
// hooks.ts
import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux'
import { AppDispatch } from 'app/store'
import { RootState } from 'app/reducer'

// Use throughout your app instead of plain `useDispatch` and `useSelector`
export const useAppDispatch = ():AppDispatch => useDispatch<AppDispatch>()
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
```

package.json
```json
{
    "dependencies": {
        "@reduxjs/toolkit": "^1.6.0",
        "axios": "^0.21.1",
        "bcryptjs": "^2.4.3",
        "body-parser": "^1.19.0",
        "connect-history-api-fallback": "^1.6.0",
        "connect-multiparty": "^2.2.0",
        "connected-react-router": "^6.9.1",
        "cookie-parser": "^1.4.5",
        "core-js": "^3.15.2",
        "cors": "^2.8.5",
        "dotenv": "^10.0.0",
        "dotenv-webpack": "^7.0.3",
        "express": "^4.17.1",
        "express-session": "^1.17.1",
        "fs": "^0.0.2",
        "jquery": "^3.6.0",
        "jsonwebtoken": "^8.5.1",
        "morgan": "^1.10.0",
        "mysql": "^2.18.1",
        "passport": "^0.4.1",
        "passport-jwt": "^4.0.0",
        "passport-local": "^1.0.0",
        "path": "^0.12.7",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-redux": "^7.2.4",
        "react-router-dom": "^5.2.0",
        "react-scripts": "4.0.3",
        "redux": "^4.1.0",
        "redux-logger": "^3.0.6",
        "redux-thunk": "^2.3.0",
        "strongpassword": "^1.1.4",
        "validator": "^13.6.0",
        "winston": "^3.3.3"
    },
    "devDependencies": {
        "@babel/cli": "^7.14.5",
        "@babel/core": "^7.14.6",
        "@babel/node": "^7.14.7",
        "@babel/plugin-proposal-class-properties": "^7.14.5",
        "@babel/plugin-transform-runtime": "^7.14.5",
        "@babel/preset-env": "^7.14.7",
        "@babel/preset-react": "^7.14.5",
        "@babel/preset-typescript": "^7.14.5",
        "@babel/register": "^7.14.5",
        "@babel/runtime": "^7.14.6",
        "@nodelib/fs.walk": "^1.2.7",
        "@types/history": "^4.7.9",
        "@types/node": "^16.0.1",
        "@types/react": "^17.0.13",
        "@types/react-dom": "^17.0.8",
        "@types/react-redux": "^7.1.17",
        "@types/react-router-dom": "^5.1.7",
        "@types/redux-logger": "^3.0.9",
        "@types/webpack-env": "^1.16.2",
        "@typescript-eslint/eslint-plugin": "^4.28.2",
        "@typescript-eslint/parser": "^4.28.2",
        "babel-eslint": "^10.0.1",
        "babel-loader": "^8.2.2",
        "babel-plugin-module-resolver": "^4.1.0",
        "chai": "^4.3.4",
        "chai-http": "^4.3.0",
        "clean-webpack-plugin": "^3.0.0",
        "copy-webpack-plugin": "^9.0.1",
        "css-loader": "^5.2.6",
        "eslint": "^7.30.0",
        "eslint-config-airbnb-base": "^14.2.1",
        "eslint-import-resolver-alias": "^1.1.2",
        "eslint-import-resolver-typescript": "^2.4.0",
        "eslint-import-resolver-webpack": "^0.13.1",
        "eslint-loader": "^2.1.2",
        "eslint-plugin-import": "^2.23.4",
        "favicons-webpack-plugin": "^5.0.2",
        "file-loader": "^6.2.0",
        "html-loader": "^2.1.2",
        "html-webpack-plugin": "^5.3.2",
        "mocha": "^9.0.2",
        "node-sass": "^6.0.1",
        "nodemon": "^2.0.9",
        "optimize-css-assets-webpack-plugin": "^6.0.1",
        "sass-loader": "^12.1.0",
        "script-loader": "^0.7.2",
        "source-map-loader": "^3.0.0",
        "style-loader": "^3.0.0",
        "tsconfig-paths-webpack-plugin": "^3.5.1",
        "typescript": "^4.3.5",
        "uglifyjs-webpack-plugin": "^2.2.0",
        "url-loader": "^4.1.1",
        "webpack": "^5.43.0",
        "webpack-cli": "^4.7.2",
        "webpack-dev-middleware": "^5.0.0",
        "webpack-dev-server": "^3.11.2",
        "webpack-hot-middleware": "^2.25.0",
        "webpack-node-externals": "^3.0.0"
    }
}
```

tsconfig.json
```json
{
    "compilerOptions": {
        "outDir": "./dist",
        "noImplicitAny": false,
        "module": "es6",
        "target": "es5",
        "jsx": "react",
        "allowJs": true,
        "strict": true,
        "moduleResolution": "node",
        "baseUrl": ".",
        "paths": {
            "app": ["./src/app/index.ts"],
            "app/*": ["./src/app/*"],
            "actions": ["./src/actions/index.ts"],
            "actions/*": ["./src/actions/*"],
            "components": ["./src/components/index.ts"],
            "components/*": ["./src/components/*"],
            "helpers": ["./src/helpers/index.ts"],
            "helpers/*": ["./src/helpers/*"],
            "services" : ["./src/services/index.ts"],
            "services/*" : ["./src/services/*"],
            "views" : ["./src/views/index.ts"],
            "views/*" : ["./src/views/*"]
        }
    },
    "include": ["./src/**/*", "./.eslintrc.js"],
    "exclude": ["./node_modules/", "./src/Tests/**/*"]
}
```

```javascript
// .Eslint.js
const path = require('path')

module.exports = {
    root: true,
    env: {
        browser: true,
        es6: true,
        node: true,
    },
    parser: '@typescript-eslint/parser',
    plugins: [
        '@typescript-eslint',
        'import',
    ],
    extends: [
        'airbnb-base',
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
        'plugin:react/recommended',
        'plugin:import/typescript',
    ],
    parserOptions: {
        project: 'tsconfig.json',
        tsconfigRootDir: __dirname,
        sourceType: 'module',
        debugLevel: false,
    },
    rules: {
        semi: ['error', 'never'],
        'no-console': 'error',
        'no-unused-vars': 1,
        // 'import/no-unresolved': 0
        // 'import/no-unresolved': [2, { caseSensitive: false }],
        '@typescript-eslint/explicit-module-boundary-types': 0,
        indent: ['error', 4],
        'import/extensions': 0,
        'no-use-before-define': 0,
        '@typescript-eslint/no-use-before-define': 1,
        'no-param-reassign': ['error', {
            props: true,
            ignorePropertyModificationsFor: [
                'state',
            ],
        }],
        'import/no-cycle': 0,
    },
    settings: {
        'import/resolver': [
            {
                webpack: {
                    config: path.join(__dirname, 'webpack.dev.config.js'),
                },
            },
            {
                typescript: {}, // this loads <rootdir>/tsconfig.json to eslint
            },
            {
                node: {
                    extensions: ['.js', '.jsx', '.ts', '.tsx'],
                    moduleDirectory: ['node_modules', 'src/'],
                    paths: ['.'],
                },
            },
            {
                alias: [
                    ['app', './src/app'],
                ],
            },
        ],
        react: {
            version: 'detect',
        },
    },
}
```

Happy to post more code, thanks in advance for the help!

**Comment by phryneas** [comment]
In 9 out of 10 cases, something like this is a circular import.

Is `loadApp` accessing your store?

**Comment by markerikson** [comment]
You appear to have a typo in your slice:

`builder.addCase(load.fullfilled`

it should be `fulfilled`, not `fullfilled` .

**Comment by hooksjam** [comment]
That solved it. Stupid mistake I apologize.

If I may, my typescript issue still persists if you could please help me with that

I'm finding in a lot of places types that I would expect to be inferred are not. 
e.g.
![image](https://user-images.githubusercontent.com/32071563/125497880-3ff67ecc-0f09-4297-b87c-49c4d1910647.png)![image](https://user-images.githubusercontent.com/32071563/125498101-e66989cb-cd34-4e17-a2f5-0ba2bfd93411.png)

I passed the RootState to the createAsyncThunk options, the docs suggested the state type should be inferred in the extraReducers but its not.

I found also my RootState itself was never inferred you can see in my reducer.ts code above I had to manually type it.

Is there anything in the typescript config that might cause this?

**Comment by markerikson** [comment]
The `state` generic arg in `createAsyncThunk` is only used for its `getState()` behavior.

The type of `state` in a reducer is the type of the `initialState` for your slice.

**Comment by hooksjam** [comment]
The initialState is correctly typed, yet even a basic reducer doesn't pick it up.
![image](https://user-images.githubusercontent.com/32071563/125500554-e7be66c5-73cd-45f4-b909-22814a8ad002.png)![image](https://user-images.githubusercontent.com/32071563/125503097-2f4759d6-a36f-4ee0-97be-ff618a58d0c6.png)

I found and resolved one circular import related to AppState. I have restarted the TS server. I found its spitting out a few errors that aren't immediately clear what they mean. How do you debug these kind of issues?

```
[Error  - 2:18:22 PM] 'signatureHelp' request failed with error.
Error processing request. Cannot read property 'getCallSignatures' of undefined
TypeError: Cannot read property 'getCallSignatures' of undefined
    at Object.getPossibleGenericSignatures (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89036:99)
    at getCandidateInfo (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98844:37)
    at Object.getSignatureHelpItems (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98792:33)
    at Object.getSignatureHelpItems (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111590:37)
    at IOSession.Session.getSignatureHelpItems (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119082:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118110:61)
    at c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:88
    at IOSession.Session.executeWithRequestId (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119487:28)
    at IOSession.Session.executeCommand (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:33)
    at IOSession.Session.onMessage (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119516:35)
    at Interface.<anonymous> (c:\Users\James\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120770:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

I thought maybe I could manually type load, but it doesn't appear to care
![image](https://user-images.githubusercontent.com/32071563/125505422-ae880c57-f8eb-4fc7-be5c-6ebccf46609f.png)


Is there any more information I provide to narrow this issue down?

**Comment by markerikson** [comment]
Would really need to see a CodeSandbox or example repo to poke at it and have a better idea what's going on here.

**Comment by hooksjam** [comment]
Okay I will put something together, ty

**Comment by hooksjam** [comment]
https://github.com/hooksjam/exampleRTK
stripped down project that will hopefully allow you to reproduce the problem when opened in VSCode
I had to do some additional configuration of VS code to get eslint/typescript to work, these settings are listed in the readme

I was able to get the type to work in a very basic sandbox 
https://codesandbox.io/s/sad-darkness-zchzz
if that might give more clues as to why this doesn't work in VSCode. 

I appreciate the help you're giving me in figuring this out.
