### ISSUE TITLE
Unnecessary errors in the log are consoled when running test commands

### ISSUE THREAD

**Issue by quzq** [reduxjs/redux-toolkit#1369]
Hi, there!

I run tests for all packages with yarn test.

The following console.error() was output in the log.
```
➤ YN0000:     console.error
➤ YN0000:       Error: rejected
➤ YN0000:           at Object.<anonymous> (C:\Users\USER\repos\redux-toolkit\packages\toolkit\src\query\tests\retry.test.ts:74:37)
➤ YN0000:           at Object.asyncJestTest (C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
➤ YN0000:           at C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:45:12
➤ YN0000:           at new Promise (<anonymous>)
➤ YN0000:           at mapper (C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
➤ YN0000:           at C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:75:41
➤ YN0000:           at runMicrotasks (<anonymous>)
➤ YN0000:           at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000:
➤ YN0000:       315 |         )
➤ YN0000:       316 |       } else {
➤ YN0000:     > 317 |         console.error(error)
➤ YN0000:           |                 ^
➤ YN0000:       318 |       }
➤ YN0000:       319 |       throw error
➤ YN0000:       320 |     }
```

This has started to occur since [buildThunks.ts](https://github.com/reduxjs/redux-toolkit/pull/1251/files#diff-0ffe77a934f2eff0ea79dcc0022def9a4888740a0ce9f2cc82e3f61212753a61) was changed in [log unhandled errors during request to console #1251](https://github.com/reduxjs/redux-toolkit/pull/1251).

**Comment by phryneas** [comment]
Yes, I know. 

So far it has just not been a priority to fix it since the tests are still working 100%, just a bit noisy, and there is a lot in the pipeline and too little time :wink: 

If you want to file a PR against the tests to mock console for them and maybe even expect these errors, that would be highly appreciated.
