### ISSUE TITLE
RTKQuery - (0 , import_react2.useState) is not a function

### ISSUE THREAD

**Issue by afternoon2** [reduxjs/redux-toolkit#1420]
Hello! I'm not sure if this is a RTK-Query related issue, but I've been digging the web for a solution for about 2 days now 😬 

I've got a package inside a lerna-driven monorepo, which is an embedded React app. I'm using Redux toolkit for state management, and I wanted to use RTK-query for data fetching as well.

Everything works fine in the browser, but when it comes to testing, I'm getting following error on and on:

`Error: Uncaught [TypeError: (0 , import_react2.useState) is not a function]`

It is related to the `@reduxjs/toolkit/dist/query/react/rtk-query-react.cjs.development.js:256:49` line in the bundle file:

```js
var _g = (0, import_react2.useState)(), requestId = _g[0], setRequestId = _g[1];
```

I've got `^17.0.2` React and ReactDOM versions. Jest configuration looks as below:

```js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  collectCoverageFrom: [
    'src/**/*.tsx',
    'src/**/*.ts',
    '!<rootDir>/node_modules/',
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  coveragePathIgnorePatterns: ['index.ts', 'src/lib/testUtils'],
  moduleNameMapper: {
    '\\.scss$': 'identity-obj-proxy',
  },
  moduleDirectories: ['node_modules', '.'],
  roots: ['<rootDir>/src'],
  reporters: ['default', 'jest-sonar'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts']
};
```

The service looks as below:

```typescript
export const service = createApi({
    reducerPath: 'service',
    baseQuery: fetchBaseQuery({
      baseUrl: API_URL,
      fetchFn,
    }),
    endpoints: (build) => ({
      loanProducts: build.query<
        LoanProductsResponsePayload,
        GetLoanProductParams
      >({
        query: (params: GetLoanProductParams) => ({
          url: 'loan-products',
          params,
        }),
      }),
      signup: build.mutation<SignupUserResponsePayload, SignupUserRequestBody>({
        query: (body) => ({
          url: 'signup',
          method: 'POST',
          body,
        }),
      }),
    }),
  });

export const { useLoanProductsQuery, useSignupMutation } = service;
```

And the failing test component inside the suite:

```typescript
import { Provider } from 'react-redux';
import store from '..';
import { render, screen } from '@testing-library/react';

test('signup endpoint hook', async () => {
    fetchMock.mockResponse(
      JSON.stringify(resPayload)
    );

    const Wrapper: React.FC = () => {
      const [load, { isError, error, isLoading, data }] = service.useSignupMutation();
    
      React.useEffect(() => {
        load(reqPayload);
      }, [load]);
    
      if (isError) {
        return <p>{error}</p>;
      }
    
      if (isLoading) {
        return <p>Loading</p>;
      }
    
      return (
        <>
          <p>{data?.email}</p>
        </>
      );
    };

   render(
      <Provider store={store}>
        <Wrapper />
      </Provider>
    );

    expect(await screen.findByText('linda.lovelace@example.com')).toBeDefined();
  });
```

**Comment by phryneas** [comment]
I'd assume that is somehow a problem with your bundler. Looking at that file, it contains 

```js
var import_react2 = __toModule(require("react"));
```

So that should definitely be there.

**Comment by EduardValentin** [comment]
Did you solve this? I have the same problem

**Comment by yashar98** [comment]
i have same error. just add '/react' for importing from query.
![001](https://user-images.githubusercontent.com/7026873/185230365-f0e4db58-8fec-44f3-9a97-8217b67b68df.png)
importing is different in react.

**Comment by Rhema7776** [comment]
> when i import uiseGetPostsQuery then the error is showing. how to solve this error
> 
> TypeError: (0 , _postsSlice__WEBPACK_IMPORTED_MODULE_1__.useGetPostsQuery) is not a function
    at PostList (main.96fbc04f3460fe045b8c.hot-update.js:35:68)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (react-dom.development.js:26096:1)
