### ISSUE TITLE
Broken Import on RTK Query

### ISSUE THREAD

**Issue by ChuckJonas** [reduxjs/redux-toolkit#1753]
Trying to run the example from the docs:
```
curl -o petstore.json https://petstore3.swagger.io/api/v3/openapi.json
npx @rtk-incubator/rtk-query-codegen-openapi --hooks petstore.json > petstore-api.generated.ts
```

**Output:**
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16088    0 16088    0     0  22982      0 --:--:-- --:--:-- --:--:-- 22950
npx: installed 101 in 11.797s
SyntaxError: Identifier expected. (1:24)
> 1 | import { createApi as  } from "@reduxjs/toolkit/query/react";
    |                        ^
  2 | import { fetchBaseQuery as  } from "@reduxjs/toolkit/query";
  3 | export const api = createApi({
  4 |     baseQuery: fetchBaseQuery({ baseUrl: "/api/v3" }),
    at e (/Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/parser-typescript.js:1:322)
    at /Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/parser-typescript.js:22:3328487
    at Object.parse (/Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/parser-typescript.js:22:3328520)
    at Object.parse$a [as parse] (/Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/index.js:12513:19)
    at coreFormat (/Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/index.js:14044:16)
    at formatWithCursor$1 (/Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/index.js:14284:14)
    at /Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/index.js:59304:12
    at Object.format (/Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/prettier/index.js:59324:12)
    at prettify (/Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/lib/utils/prettier.js:53:21)
    at /Users/charlesjonas/.npm/_npx/79935/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/lib/bin/cli.js:92:52 {
  loc: { start: { line: 1, column: 24 } },
  codeFrame: '> 1 | import { createApi as  } from "@reduxjs/toolkit/query/react";\n' +
    '    |                        ^\n' +
    '  2 | import { fetchBaseQuery as  } from "@reduxjs/toolkit/query";\n' +
    '  3 | export const api = createApi({\n' +
    '  4 |     baseQuery: fetchBaseQuery({ baseUrl: "/api/v3" }),'
 ```

**Comment by Meligy** [comment]
There's an open issue for that in the code generation repository https://github.com/rtk-incubator/rtk-query-codegen/issues/83.

**Comment by phryneas** [comment]
Does that happen in the version from https://github.com/reduxjs/redux-toolkit/pull/1680 too?

**Comment by Meligy** [comment]
> Does that happen in the version from #1680 too?

If it's the dependency issue I suspect, I'd expect it to happen there too yeah, as it has the dependency.

**Comment by phryneas** [comment]
Well, we're not using ts-morph, so it would only be possible if TS itself had changed their internal AST.

**Comment by YohayBar** [comment]
same issue here :(

**Comment by ChuckJonas** [comment]
That appears to be what happened:

![thumbnail_image001](https://user-images.githubusercontent.com/5217568/142454827-0dace10a-9684-43e9-ad5e-974144841433.png)


Should the ts dep be version locked?  Did they break semantic versioning on this one?

**Comment by phryneas** [comment]
TS always breaks something :(

I'll guess we will have to lock that version for the Codegen in the future.

**Comment by markerikson** [comment]
@ChuckJonas TS explicitly does _not_ follow semver itself.

**Comment by ChuckJonas** [comment]
@markerikson I didn't know that!  Looks like they promise no breaking changes in patches.  I guess you'd just want to pin to the minor version then. EG use `~` instead of `^`

**Comment by phryneas** [comment]
Why on earth they would add a new parameter at the beginning instead of the end evades me though. Super frustrating.

**Comment by dieseldjango** [comment]
I'm just getting started using the openapi codegen and getting this error on one of my team's openapi specs, where codegen is trying to export a type named "0":

```
npx @rtk-query/codegen-openapi api-config/*.json
Generating ../src/core/apis/config.ts
SyntaxError: Declaration or statement expected. (1007:1)
  1005 |     migrationId?: string;
  1006 | };
> 1007 | export type 0 = {
       | ^
  1008 |     blockKey?: Items;
  1009 |     name?: string;
  1010 |     version?: string;
```
The spec I'm working with seems otherwise fine, it lints ok with swagger-cli and speccy. Is this problem possibly related to this issue?

**Comment by Meligy** [comment]
@dieseldjango this is a separate area from the one in this issue. I think you'll need to create a new issue for it, and include a bit of your Swagger JSON for this bit.
