### ISSUE TITLE
Codegen - Enum integer values

### ISSUE THREAD

**Issue by grumpyTofu** [reduxjs/redux-toolkit#1788]
Running into an issue when I have an enum in my openapi schema.

```json
"SpecialTypes": {
        "enum": [
          0,
          1,
          2
        ],
        "type": "integer",
        "format": "int32"
      },
```

Here is the stack trace

```bash
% yarn openapi
yarn run v1.22.10
$ esr openapi.config.ts && yarn gen-api && yarn gen-schema
Successfully updated openapi config
$ npx @rtk-incubator/rtk-query-codegen-openapi@0.5.1 --hooks ./openapi.config.json --baseQuery ./src/app/apiBaseQuery.ts:apiBaseQueryWithDeauth --file ./src/app/finsense-api.generated.ts
npx: installed 105 in 5.81s
TypeError: s.replace is not a function
    at escapeString (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:17825:18)
    at escapeNonAsciiString (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:17830:13)
    at Object.getLiteralText (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:14695:34)
    at getLiteralTextOfNode (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:111632:23)
    at emitLiteral (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:109021:24)
    at pipelineEmitWithHintWorker (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:108822:32)
    at pipelineEmitWithHint (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:108448:17)
    at pipelineEmitWithComments (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:112002:13)
    at pipelineEmit (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:108388:13)
    at emitExpression (/Users/austinfelix/.npm/_npx/61405/lib/node_modules/@rtk-incubator/rtk-query-codegen-openapi/node_modules/typescript/lib/typescript.js:108372:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

problem is resolved by manually changing the enum integers into strings like so:

```json
"SpecialTypes": {
        "enum": [
          "0",
          "1",
          "2"
        ],
        "type": "integer",
        "format": "int32"
      },
```

**Comment by floatrx** [comment]
```
npx @rtk-incubator/rtk-query-codegen-openapi openapi-config.json
Generating ./src/store/testApi.ts
TypeError: s.replace is not a function
    at escapeString (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:17825:18)
    at escapeNonAsciiString (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:17830:13)
    at Object.getLiteralText (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:14695:34)
    at getLiteralTextOfNode (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111651:23)
    at emitLiteral (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:109040:24)
    at pipelineEmitWithHintWorker (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108841:32)
    at pipelineEmitWithHint (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108467:17)
    at pipelineEmitWithComments (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:112021:13)
    at pipelineEmit (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108407:13)
    at emitExpression (/Users/floatrx/Projects/CORE/support-app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108391:13)
```

same issue (( 
+ same fix!
```
...
        "enum": [
          "1",
          "2",
          "3",
          "4"
        ],
...
````

**Comment by floatrx** [comment]
## My temporary solution -> "openapi-download" 
// simple util script (nodejs)

```json

  "scripts": {
    "openapi:download": "node openapi-download && npx @rtk-incubator/rtk-query-codegen-openapi openapi-config.ts"
  },

```
I used `@rtk-incubator/rtk-query-codegen-openapi` instead of `@rtk-query/codegen-openapi` -> coz:
```
npx @rtk-query/codegen-openapi openapi-config.ts
npx: installed 64 in 13.608s
Encountered a TypeScript configfile, but neither esbuild-runner nor ts-node are installed.
```

Downloader `openapi-download.js`
```js
const fs = require('fs');
const util = require('util');
const exec = util.promisify(require('child_process').exec);

// Config
const specsUrl = 'https://domain.com/openapi.json'; // <----------------- download url
const rawFileName = './schemas.json'; // <----------------- same as 'schemaFile' in config.json
const schemaFile = rawFileName; // rewrite mode

// Step 1
const download = () =>
  new Promise(async (resolve, reject) => {
    console.log('Downloading JSON from:', specsUrl);

    // Download latest openapi specs
    await exec(`curl ${specsUrl} -o ${rawFileName}`, (error, stdout) => {
      if (error) {
        console.error('Failed. Error: ' + error);
        reject(error);
      }
      console.log('Downloaded');
      resolve(require(rawFileName));
    });
  });

// Step 2
const fixEnums = (openapi) => {
  console.log('[CASE] Start fix enums... [1,2,3]->["1","2","3"]');

  if (!fs.existsSync(rawFileName)) {
    return console.error(`File ${rawFileName} not exists`);
  }

  if (!openapi.components.schemas) {
    console.error('Bad schemas');
    return;
  }

  for (let scheme in openapi.components.schemas) {
    let _enum = openapi.components.schemas[scheme].enum;
    const isNumbersOnly = !!_enum?.every((v) => typeof v === 'number'); // all array items are numbers!
    if (isNumbersOnly) {
      openapi.components.schemas[scheme].enum = _enum.map((v) => String(v));
    }
  }
  return openapi;
};

// Step 3
const save = (data) => {
  fs.writeFile(schemaFile, JSON.stringify(data), (error) => {
    error ? console.error('File save error', error) : console.log('File saved successfully!\n');
  });
};

// Actualize
download().then(fixEnums).then(save);
```

ps; I will wait for an official fix

**Comment by lindapaiste** [comment]
This is the relevant part of the RTK codegen code:
```
 if (schema.enum) {
      // enum -> union of literal types
      const types = schema.enum.map((s) => {
        if (s === null) return cg.keywordType.null;
        if (typeof s === "boolean")
          return s
            ? factory.createLiteralTypeNode(
                ts.factory.createToken(ts.SyntaxKind.TrueKeyword)
              )
            : factory.createLiteralTypeNode(
                ts.factory.createToken(ts.SyntaxKind.FalseKeyword)
              );
        return factory.createLiteralTypeNode(factory.createStringLiteral(s));
      });
      return types.length > 1 ? factory.createUnionTypeNode(types) : types[0];
    }
```

There is a check for `null` and `boolean` avlues but not for `number`.  So it calls `factory.createStringLiteral(s)` with a `number` and fails as this function requires a `string`.  It seems pretty straight-forward to fix -- I'll see what I can do 🤞.

**Comment by lindapaiste** [comment]
It turns out that this has already been [fixed in the `oazapfts` repo](https://github.com/cellular/oazapfts/pull/169).  That PR was approved and merged but they haven't put out a new release since then 😞

**Comment by henkkasoft** [comment]
Would be great to have a new release soon, because of this

**Comment by GeorchW** [comment]
I think this should already be fixed with the new version

**Comment by iliapnmrv** [comment]
@GeorchW no its not  :(
issue persists in v2.2.3

**Comment by Getterac7** [comment]
> @GeorchW no its not :( issue persists in v2.2.3

I'm depending on `"@reduxjs/toolkit": "^1.9.3"` and it works great for me; probably works in v2.2.3 as well but I haven't tried.

Using https://github.com/reduxjs/redux-toolkit/issues/1788#issuecomment-999086924 as a starting point...

1. Remove the fixEnums function call on the last line: `download().then(save).then(generate);`
2. Modify your config.ts/config.js file to use the enum type flag:
```js
const config = {
  ...
  useEnumType: true,
}
```

And that's it! Re-run the script to generate your type definitions and it should have proper Typescript enums.

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.
