### ISSUE TITLE
RTKQ - localStorage is not defined in prepareHeaders when running query from getStaticProps

### ISSUE THREAD

**Issue by agusterodin** [reduxjs/redux-toolkit#1812]
I am attempting to use RTK query with getStaticProps. Unfortunately localStorage is not defined in prepareHeaders when running a query from getStaticProps.

I understand that this is because for this particular query, RTK query is being ran server side, not client side. Ideally, I should be able to detect if localStorage is undefined and just skip that logic if so. I don't need to use a bearer token for this particular endpoint anyway.

**My getStaticProps function**

```
export const getStaticProps = wrapper.getStaticProps(store => async () => {
  store.dispatch(authSubscriptionApiEndpoints.getAllSubscriptionDetails.initiate())
  await Promise.all(authApi.util.getRunningOperationPromises())
  const allSubscriptionDetails = authSubscriptionApiEndpoints.getAllSubscriptionDetails.select()(store.getState())
  console.log('allSubscriptionDetails', allSubscriptionDetails)
  return { props: {} }
})
```

**My baseQuery**

```
const baseQuery = fetchBaseQuery({
  baseUrl: `${process.env.REACT_APP_AUTH_URL || process.env.NEXT_PUBLIC_AUTH_URL}/api`,
  prepareHeaders: headers => {
    const accessToken = localStorage.getItem('access_token')
    if (accessToken) headers.set('authorization', `Bearer ${accessToken}`)
    return headers
  }
})
```

**The error I am receiving**

```
allSubscriptionDetails {
  status: 'rejected',
  endpointName: 'getAllSubscriptionDetails',
  requestId: 'EXKDYyd-8EAQroxmj9VKE',
  startedTimeStamp: 1638920128755,
  error: {
    name: 'ReferenceError',
    message: 'localStorage is not defined',
    stack: 'ReferenceError: localStorage is not defined\n' +
      '    at prepareHeaders (webpack-internal:///./carbon-lib-ui/authentication/api/base.ts:11:29)\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:277:42\n' +
      '    at step (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:23:23)\n' +
      '    at Object.next (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:4:53)\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:110:65\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at __async (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:92:12)\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:256:39\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:568:42\n' +
      '    at step (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:23:23)'
  },
  isUninitialized: false,
  isLoading: false,
  isSuccess: false,
  isError: true
}
``` 

I tried changing my prepareHeaders function to 
```
prepareHeaders: headers => {
    if (window !== undefined) {
      const accessToken = localStorage.getItem('access_token')
      if (accessToken) headers.set('authorization', `Bearer ${accessToken}`)
    }
    return headers
  }
```

but then I get a similar error

```
allSubscriptionDetails {
  status: 'rejected',
  endpointName: 'getAllSubscriptionDetails',
  requestId: 'brF2TzVhGK8OTIuCbEaNM',
  startedTimeStamp: 1638920258159,
  error: {
    name: 'ReferenceError',
    message: 'window is not defined',
    stack: 'ReferenceError: window is not defined\n' +
      '    at prepareHeaders (webpack-internal:///./carbon-lib-ui/authentication/api/base.ts:11:9)\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:277:42\n' +
      '    at step (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:23:23)\n' +
      '    at Object.next (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:4:53)\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:110:65\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at __async (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:92:12)\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:256:39\n' +
      '    at /Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:568:42\n' +
      '    at step (/Users/Jeff/Documents/CarbonReach/cr-website-next/node_modules/@reduxjs/toolkit/dist/query/rtk-query.cjs.development.js:23:23)'
  },
  isUninitialized: false,
  isLoading: false,
  isSuccess: false,
  isError: true
}
```

The code works fine and query succeeds if I comment out the two lines related to localStorage entirely.

**Comment by markerikson** [comment]
Yeah, this is really a Node+Next.js question, rather than an RTK question.  You're on the right track, but need to write it more cautiously:

```js
if (typeof window !== "undefined") {
  // Client-side-only code
}
```

**Comment by agusterodin** [comment]
Thanks!
