### ISSUE TITLE
Action created using createAsyncThunk shows to be undefined upon import

### ISSUE THREAD

**Issue by 0xts** [reduxjs/redux-toolkit#2011]
I'm using redux-toolkit with electron ( CommonJS module system). I've a initSlice file, like this -

```
const checkDisk = createAsyncThunk("init/checkDisk", async () => {
  // check disk for documents
  const files = await scanDisk();
  return files;
});

const initSlice = createSlice({
  name: "init",
  initialState,
  reducers: {},
  extraReducers(builder) {
    builder
      .addCase(checkDisk.pending, (state, action) => {
        state.checkingDiskForFiles = true;
      })
      .addCase(checkDisk.fulfilled, (state, action) => {
        state.checkingDiskForFiles = false;
        state.docs = action.payload;
      })
      .addCase(checkDisk.rejected, (state, action) => {
        state.checkingDiskForFiles = false;
        state.error = action.error;
      });
  },
});


exports.checkDisk = checkDisk;

module.exports = initSlice;
```
I imported this file in my electron main.js file, which looks something like this - 

```
const {app} = require("electron");
const {checkDisk} = require("./redux/initSlice"); 
const store = require("./redux/store");

app.on("ready", async () => {
   // omitting the code to create a browser window and load an html file.
   store.dispatch(checkDisk());
});
```
I'm bundling the code with webpack@5.68.0 using "electron-main" as the target in the config and when I run electron using the bundled file, it gives a unhandled promise rejection warning that checkDisk is not a function. Here's the stack trace - 

```
(node:17193) UnhandledPromiseRejectionWarning: TypeError: checkDisk is not a function
    at _callee$ (/home/user/Development/Web/Orange/dist/main.js:76598:26)
    at tryCatch (/home/user/Development/Web/Orange/dist/main.js:71596:40)
    at Generator.invoke [as _invoke] (/home/user/Development/Web/Orange/dist/main.js:71827:22)
    at Generator.next (/home/user/Development/Web/Orange/dist/main.js:71652:21)
    at asyncGeneratorStep (/home/user/Development/Web/Orange/dist/main.js:46:24)
    at _next (/home/user/Development/Web/Orange/dist/main.js:68:9)
    at /home/user/Development/Web/Orange/dist/main.js:75:7
    at new Promise (<anonymous>)
    at App.<anonymous> (/home/user/Development/Web/Orange/dist/main.js:64:12)
    at App.emit (node:events:390:28)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:17193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
The issue is only with createAsyncThunk actions and not the other ones. A console log of `checkDisk` prints `undefined` Is it some issue because of bundling with Webpack? I've tried using ESM as well, it still exists.

**Comment by 0xts** [comment]
```
node - v17.4.0
electron - v17.0.0
npm - v8.3.1
```
I felt that it was due to bundling and tried to run it without bundling, same thing happened. I guess I'll just manually create thunks.
