### ISSUE TITLE
RTK generateEndpoints throws typescript error: Trace: TypeError: Cannot read property 'pos' of undefined

### ISSUE THREAD

**Issue by isidornygren** [reduxjs/redux-toolkit#2425]
Running the RTK code generation as described in the docs by running `npx @rtk-query/codegen-openapi openapi-config.ts` works fine without any issues.

However, running exactly the same config using the `generateEndpoints` function produces what looks like a typescript error. I've tried running it both using Node and esbuild-runner but it still errors. I've tried using different openapi endpoints but I still receive the same error when trying to run the function programmatically.

### Setup
```typescript
// src/store/emptyApi.ts
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const emptySplitApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  endpoints: () => ({}),
});
```

```typescript
// apiConfig.ts
import type { ConfigFile } from '@rtk-query/codegen-openapi';

const apiConfig: ConfigFile = {
  // Using an example openapi endpoint found online
  schemaFile: 'https://petstore.swagger.io/v2/swagger.json',
  apiFile: './src/store/emptyApi.ts',
  apiImport: 'emptySplitApi',
  outputFile: './src/model/generated/api.ts',
  exportName: 'api',
  hooks: true,
};

export default apiConfig;
```

```typescript
// generateApi.ts (run through node or esbuild-runner)
const config = {
  schemaFile: 'https://petstore.swagger.io/v2/swagger.json',
  apiFile: './src/store/emptyApi.ts',
  apiImport: 'emptySplitApi',
  outputFile: './src/model/generated/api.ts',
  exportName: 'api',
  hooks: true,
};

generateEndpoints(config).catch(console.trace);
```

### Output

```
Trace: TypeError: Cannot read property 'pos' of undefined
    at emitNodeList (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111266:48)
    at emitList (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111158:13)
    at emitObjectLiteralExpression (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:109538:13)
    at pipelineEmitWithHintWorker (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108863:32)
    at pipelineEmitWithHint (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108479:17)
    at pipelineEmitWithComments (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:112033:13)
    at pipelineEmit (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108419:13)
    at emitExpression (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108403:13)
    at emitNodeList (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111271:25)
    at emitExpressionList (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111161:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by phryneas** [comment]
Have you tried calling `parseConfig` before?

See https://github.com/reduxjs/redux-toolkit/blob/a5cf61b366f23a868548d1ca7d56350c76610cbf/packages/rtk-query-codegen-openapi/src/bin/cli.ts#L56-L71

**Comment by isidornygren** [comment]
> Have you tried calling `parseConfig` before?
> 
> See
> 
> https://github.com/reduxjs/redux-toolkit/blob/a5cf61b366f23a868548d1ca7d56350c76610cbf/packages/rtk-query-codegen-openapi/src/bin/cli.ts#L56-L71

Yes, I've tried it and it gave me what looked like the same error. However, when double checking i saw that it was slightly different (Albeit still seems to be a typescript parsing error, and I still have no idea why it's happening):
```
Trace: TypeError: Cannot read property 'end' of undefined
    at emitTupleType (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:109373:76)
    at pipelineEmitWithHintWorker (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108569:32)
    at pipelineEmitWithHint (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108479:17)
    at pipelineEmitWithComments (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:112033:13)
    at pipelineEmit (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108419:13)
    at emit (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108392:13)
    at emitNodeList (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111271:25)
    at emitList (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111158:13)
    at emitUnionType (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:109388:13)
    at pipelineEmitWithHintWorker (/Users/***/***/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108574:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Using this code:
```typescript
const config = parseConfig({
  schemaFile: 'https://petstore.swagger.io/v2/swagger.json',
  apiFile: './src/store/emptyApi.ts',
  apiImport: 'emptySplitApi',
  outputFile: './src/model/generated/api.ts',
  exportName: 'api',
  hooks: true
});

config.forEach((c) => generateEndpoints(c).catch(console.trace));
```

**Comment by kdevan** [comment]
I'm running into the same issue:
```
TypeError: Cannot read properties of undefined (reading 'end')
    at emitTupleType (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:109480:76)
    at pipelineEmitWithHintWorker (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108676:32)
    at pipelineEmitWithHint (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108586:17)
    at pipelineEmitWithComments (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:112140:13)
    at pipelineEmit (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108526:13)
    at emit (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108499:13)
    at emitNodeList (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111378:25)
    at emitList (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:111265:13)
    at emitUnionType (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:109495:13)
    at pipelineEmitWithHintWorker (/app/node_modules/@rtk-query/codegen-openapi/node_modules/typescript/lib/typescript.js:108681:32)
```

Also tried adding parseConfig but still getting the same error. I did have this working in a previous version, running into this after updating react and redux to @latest versions.

**Comment by kdevan** [comment]
Ah yeah, didn't think of that. Currently, Typescript 4.7.4. I'll test with 4.5.2 and update here.

**Comment by jkirkpatrick24** [comment]
I bumped up against this too. Using typescript 4.7.4 throws the error described above, but reverting to typescript v4.5.2 fixes it.

**Comment by phryneas** [comment]
Could you take a look what changed between those versions and if you could come up with a fix?

**Comment by kdevan** [comment]
`filterEndpoints` and `endpointOverrides` ended up being the culprits. If you add them to the configuration with an empty array as the value then it works. Both of these parameters must have an empty array as a value, both parameters trigger the error. 

```
{
    ...
    filterEndpoints: [],
    endpointOverrides: [],
}
```

**Comment by isidornygren** [comment]
Reverting to typescript version `4.5.2` unfortunately does not seem to change anything for me, I've tried forcing the rtk-query codegen typescript version by adding:
```json
{
  "devDependencies": {
     ...
     "typescript": "=4.5.2"
  },
  "resolutions": {
    "@rtk-query/codegen-openapi/typescript": "=4.5.2"
  },
}
```
But still getting the same issue:
```
Trace: TypeError: Cannot read property 'end' of undefined
    at emitTupleType (/Users/***/***/node_modules/typescript/lib/typescript.js:109342:76)
    at pipelineEmitWithHintWorker (/Users/***/***/node_modules/typescript/lib/typescript.js:108538:32)
    at pipelineEmitWithHint (/Users/***/***/node_modules/typescript/lib/typescript.js:108448:17)
    at pipelineEmitWithComments (/Users/***/***/node_modules/typescript/lib/typescript.js:112002:13)
    at pipelineEmit (/Users/***/***/node_modules/typescript/lib/typescript.js:108388:13)
    at emit (/Users/***/***/node_modules/typescript/lib/typescript.js:108361:13)
    at emitNodeList (/Users/***/***/node_modules/typescript/lib/typescript.js:111240:25)
    at emitList (/Users/***/***/node_modules/typescript/lib/typescript.js:111127:13)
    at emitUnionType (/Users/***/***/node_modules/typescript/lib/typescript.js:109357:13)
    at pipelineEmitWithHintWorker (/Users/***/***/node_modules/typescript/lib/typescript.js:108543:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Running `yarn list --pattern typescript`
```
yarn list v1.22.15
*omitted*
└─ typescript@4.5.2
✨  Done in 0.78s.
```

**Comment by lindapaiste** [comment]
I am able to reproduce this error in TS version 4.7.4 (but not on 4.3.5).  I am running Node.js version 16.13.0 on Windows.

I'm hoping that I'll get a chance to dig into it and figure out how we can make the codegen compatible with the latest TS version.

I'm not sure at this point if the issue would occur if both the app and the codegen are using v4.7.4.  When I saw the error it was with the app on the latest 4.7.4 but the codegen will load its own version fitting the specified range `"typescript": ">=4.1 <=4.5"`.

**Comment by kdevan** [comment]
Yeah, in my project `oazapfts` itself is using `typescript` 4.7.4 while `rtk-query-codegen-openapi` is using 4.5.5. Since `oazapfts` is used for typescript generation, nodes are being generated using 4.7.4 and then being processed by this library using 4.5.5.

In my case this is due to how I have yarn set up, using `yarn` 3.2.1 with `nodeLinker: node-modules` in `.yarnrc.yml`.

I tried adding a resolution to force everything to use 4.7.4 and everything is working so far:
```
"resolutions": {
  "typescript": "4.7.4"
}
```

Obviously this is risky to force libraries to use a version they don't expect but for now it's allowing development on this front to continue. :)

**Comment by DiFuks** [comment]
I get the same error (the project uses yarn pnp):

```
Trace: TypeError: Cannot read properties of undefined (reading 'end')
    at emitCaseBlock (/Users/difuks/WebstormProjects/auth/.yarn/cache/typescript-patch-1777c0c0dd-858c61fa63.zip/node_modules/typescript/lib/typescript.js:110393:73)
    at pipelineEmitWithHintWorker (/Users/difuks/WebstormProjects/auth/.yarn/cache/typescript-patch-1777c0c0dd-858c61fa63.zip/node_modules/typescript/lib/typescript.js:108781:32)
```
