### ISSUE TITLE
Cannot run codegen CLI command on .cts or .cjs files (CommonJS)

### ISSUE THREAD

**Issue by Macludde** [reduxjs/redux-toolkit#2437]
I have a project which uses Vite and thus also uses `type:"module"` in its package.json. 

### Error description
When running `npx @rtk-query/codegen-openapi` I get the following error:

```  
const err = new Error(getErrRequireEsmMessage(filename, parentPath, packageJsonPath))
              ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:/.../src/api/generationConfig.ts
require() of ES modules is not supported.
require() of /.../src/api/generationConfig.ts from /.../node_modules/@rtk-query/codegen-openapi/lib/bin/cli.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /.../package.json.
```
### Reason for error
The above error is caused by the config file being inside the package.json project whilst also having `type: "module"` specified. One fix to get around this is declaring generationConfig.ts as generationConfig.cts instead to tell it to use CommonJS imports instead of ESM.

However, this doesn't work with `@rtk-query/codegen-openapi` as in [the cli file](https://github.com/reduxjs/redux-toolkit/blob/666f18203db5e62616733fb082ea38178814715c/packages/rtk-query-codegen-openapi/src/bin/cli.ts), on line 46, the regex for checking if the path given is to a correct file is as follows 
`/\.(jsx?|tsx?|jsonc?)?$/`
This doesn't match to files ending in .cjs or .cts

### Possible solution
An easy fix would be to change the regex to
`/\.(c?(jsx?|tsx?)|jsonc?)?$/`

**Comment by philjones88** [comment]
Hit this issue too. Trying to make private NPM packages of our generated files to save having multiple copies all over the place.

**Comment by Macludde** [comment]
Part of [@rtk-query/codegen-openapi@1.0.0-alpha.2](https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%401.0.0-alpha.2)

**Comment by philjones88** [comment]
@Macludde I've updated to that package but still hit the issue:

```
/Users/philjones/Documents/<redacted>/node_modules/ts-node/dist-raw/node-internal-errors.js:46
  const err = new Error(getErrRequireEsmMessage(filename, parentPath, packageJsonPath))
              ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/philjones/Documents/<redacted>/openapi-config.ts
require() of ES modules is not supported.
require() of /Users/philjones/Documents/<redacted>/openapi-config.ts from /Users/philjones/Documents/<redacted>/node_modules/@rtk-query/codegen-openapi/lib/bin/cli.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /Users/philjones/Documents/<redacted>/package.json.

    at createErrRequireEsm (/Users/philjones/Documents/<redacted>/node_modules/ts-node/dist-raw/node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (/Users/philjones/Documents/<redacted>/node_modules/ts-node/dist-raw/node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (/Users/philjones/Documents/<redacted>/node_modules/ts-node/src/index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at run (/Users/philjones/Documents/<redacted>/node_modules/@rtk-query/codegen-openapi/src/bin/cli.ts:59:26)
    at Object.<anonymous> (/Users/philjones/Documents/<redacted>/node_modules/@rtk-query/codegen-openapi/src/bin/cli.ts:53:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by Macludde** [comment]
Your config file needs to be a .cts files and not .ts (and .cjs instead of .js). The change introduced by the PR above simply expanded the regex check to allow for .cts and .cjs files for the config.

In a regular project all .ts and .js files are automatically marked as CommonJS but when `"type": "module"` is used in the 
`package.json`, it is instead marked as using ES modules.
