### ISSUE TITLE
Codegen: S2OError: (Patchable) parameter.type is mandatory for non-body parameters

### ISSUE THREAD

**Issue by mertohancan** [reduxjs/redux-toolkit#2707]
When I run the command `npx @rtk-query/codegen-openapi openapi-config.json` to generate code, I got error in the below

```
Generating ./src/store/coreApi.ts
S2OError: (Patchable) parameter.type is mandatory for non-body parameters
    at throwError (/Users/mertohancan/.npm/_npx/17556/lib/node_modules/@rtk-query/codegen-openapi/node_modules/swagger2openapi/index.js:39:15)
    at processParameter (/Users/mertohancan/.npm/_npx/17556/lib/node_modules/@rtk-query/codegen-openapi/node_modules/swagger2openapi/index.js:540:17)
    at processPaths (/Users/mertohancan/.npm/_npx/17556/lib/node_modules/@rtk-query/codegen-openapi/node_modules/swagger2openapi/index.js:951:30)
    at main (/Users/mertohancan/.npm/_npx/17556/lib/node_modules/@rtk-query/codegen-openapi/node_modules/swagger2openapi/index.js:1186:5)
    at /Users/mertohancan/.npm/_npx/17556/lib/node_modules/@rtk-query/codegen-openapi/node_modules/swagger2openapi/index.js:1555:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  options: {
    original: {
      swagger: '2.0',
      info: [Object],
      paths: [Object],
      definitions: [Object]
    },
    text: 'swagger: "2.0"\n' +
      'info:\n' +
.
.
.

```

> openapi-config.json:

```
{
    "schemaFile": "./swagger.json",
    "apiFile": "./src/store/baseApi.ts",
    "apiImport": "baseApi",
    "outputFile": "./src/store/coreApi.ts",
    "exportName": "coreApi",
    "hooks": true
  }

```

> src/baseApi.ts

```
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const emptySplitApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  endpoints: () => ({}),
});
```

**Comment by phryneas** [comment]
That looks like an error from the internally used `swagger2openapi` library. Maybe you take a look there if someone can help you?

**Comment by mertohancan** [comment]
It may be. I can generate that code with [openapi-typescript-codegen](https://www.npmjs.com/package/openapi-typescript-codegen)(not related with redux).  So I suspected it might be library related. Maybe it could happen to someone.
