### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'type')  at Object.addCase (mapBuilders.ts:158:1)

### ISSUE THREAD

**Issue by m-nathani** [reduxjs/redux-toolkit#2960]
I am Defining a Pre-Typed `createAsyncThunk`

As of RTK 1.9, you can define a "pre-typed" version of `createAsyncThunk` that can have the types for state, dispatch,  as shown in the [usage-with-typescript#createasyncthunk](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk)

```ts

type RootState = ReturnType<typeof store.getState>;
type AppDispatch = AppStore['dispatch'];

export const createAppAsyncThunk = createAsyncThunk.withTypes<{
  state: RootState;
  dispatch: AppDispatch;
  rejectValue: { errorMessage: string };
}>();
```

And using the above to create a async thunk action as follows:

```ts
export const handleCommunication = createAppAsyncThunk<
  { template: Template; removeTemplateId: string | number } | null,
  { template: Template; messageLocale: string; communicationItemId: string | number }
>(
  'template/sendReservationMessage',
  async (
    { template, messageLocale, communicationItemId },
    { signal, rejectWithValue, getState }
  ) => {
    try {
      const state = getState();
      const something: unkown;

      // ... some business logics

      return something 
    } catch (err) {
      return rejectWithValue({
        errorMessage: (err as SerializedError).message || (err as string),
      });
    }
  }
);
```

However i am getting the error as :

```bash
mapBuilders.ts:158 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at Object.addCase (mapBuilders.ts:158:1)
    at extraReducers (slice.ts:175:1)
    at executeReducerBuilderCallback (mapBuilders.ts:194:1)
    at buildReducer (createSlice.ts:341:1)
    at reducer (createSlice.ts:370:1)
    at redux.js:468:1
    at Array.forEach (<anonymous>)
    at assertReducerShape (redux.js:466:1)
    at combineReducers (redux.js:531:1)
    at configureStore (configureStore.ts:162:1)
```

**P.S: note i dont have two thunks of the same `typePrefix` too...**

**Comment by m-nathani** [comment]
> I'm sorry, we fixed this over in #2885 but did not have a new release yet. You can use the fixed build by following the instructions over in https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/2885/builds/313875

thanks @phryneas , do we know any expected date to release the fix? 

Moreover, what i understood from the link is to install the package using this 
```bash
npm i https://pkg.csb.dev/reduxjs/redux-toolkit/commit/9b1acb3d/@reduxjs/toolkit
```

**Comment by markerikson** [comment]
Yeah, I'm probably going to try to push out a 1.9.1 in the next day or so with the fixes we do have, and do a 1.9.2 later with any other fixes.

**Comment by m-nathani** [comment]
@markerikson FYI: getting this error using `1.9.1`

```bash
Uncaught Error: addCase cannot be called with two reducers for the same action type
    at Object.addCase (mapBuilders.ts:163:1)
    at extraReducers (slice.ts:197:1)
    at executeReducerBuilderCallback (mapBuilders.ts:194:1)
    at buildReducer (createSlice.ts:341:1)
    at reducer (createSlice.ts:370:1)
    at redux.js:468:1
    at Array.forEach (<anonymous>)
    at assertReducerShape (redux.js:466:1)
    at combineReducers (redux.js:531:1)
    at configureStore (configureStore.ts:162:1)
addCase @ mapBuilders.ts:163
extraReducers @ slice.ts:197
executeReducerBuilderCallback @ mapBuilders.ts:194
buildReducer @ createSlice.ts:341
reducer @ createSlice.ts:370
(anonymous) @ redux.js:468
assertReducerShape @ redux.js:466
combineReducers @ redux.js:531
configureStore @ configureStore.ts:162
setupStore @ index.ts:16
./src/redux-store/index.ts @ index.ts:23
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/App.tsx @ plus.svg:44
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/index.tsx @ useFetchCommunication.ts:33
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
```

**Comment by markerikson** [comment]
Cool! Sounds like I can go ahead and close this, then.
