### ISSUE TITLE
Creating store with extra reducers not working in test

### ISSUE THREAD

**Issue by matthewvero** [reduxjs/redux-toolkit#2962]
I'm trying to create a store to use in test but it is throwing the following error when I try to run tests:
` FAIL  src/_tests_/features/checkout/components/DeliveryDetails.test.jsx
  DeliveryDetails
    × Opens change post code modal (5 ms)

  ● DeliveryDetails › Opens change post code modal

    TypeError: Cannot read property 'endpoints' of undefined

      120 |     );
      121 |     [
    > 122 |       customerApi.endpoints.updateGuestDetails.matchFulfilled,
          |                   ^
      123 |       customerApi.endpoints.guestLogin.matchFulfilled,
      124 |       customerApi.endpoints.login.matchFulfilled,
      125 |       customerApi.endpoints.validate2FA.matchFulfilled,

      at extraReducers (src/store/basketSlice.js:122:19)
      at executeReducerBuilderCallback (node_modules/@reduxjs/toolkit/src/mapBuilders.ts:194:3)
      at buildReducer (node_modules/@reduxjs/toolkit/src/createSlice.ts:306:11)
      at reducer (node_modules/@reduxjs/toolkit/src/createSlice.ts:323:33)
      at node_modules/redux/lib/redux.js:372:24
          at Array.forEach (<anonymous>)
      at assertReducerShape (node_modules/redux/lib/redux.js:370:25)
      at combineReducers (node_modules/redux/lib/redux.js:435:5)
      at configureTestStore (src/_tests_/testHelpers.js:17:38)
      at ReduxProvider (src/_tests_/testHelpers.js:39:17)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:829:32)
      at renderElement (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:643:26)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:707:46)
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/src/Utils.js:100:18)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:707:20)
      at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:411:22)
      at shallow (node_modules/enzyme/src/shallow.js:10:10)
      at getWrapper (src/_tests_/features/checkout/components/DeliveryDetails.test.jsx:18:17)
      at Object.<anonymous> (src/_tests_/features/checkout/components/DeliveryDetails.test.jsx:136:21)
      at TestScheduler.scheduleTests (node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/react-scripts/node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:173:3)`

This is the store config:
```
const configureTestStore = (initialState) => {
  const middleware = [
    thunk,
    api.middleware,
  ];

  const rootReducer = combineReducers({
    basket: basketReducer,
    menu: menuReducer,
    session: sessionReducer,
    loyalty: loyaltyReducer,
    [api.reducerPath]: api.reducer,
  });

  const enhancers = [];
  const windowIfDefined = typeof window === 'undefined' ? null : window;
  if (windowIfDefined && windowIfDefined.__REDUX_DEVTOOLS_EXTENSION__) {
    enhancers.push(windowIfDefined.__REDUX_DEVTOOLS_EXTENSION__());
  }
  return createStore(
    rootReducer,
    initialState,
    compose(applyMiddleware(...middleware), ...enhancers)
  );
};

export const ReduxProvider = ({ children, initialState }) => {
  const store = configureTestStore(initialState);
  return (
    <Provider store={store}>{children}</Provider>
  );
};
```
It's identical to the set up of our actual store.

The extra reducer throwing the error: 
```
 [
      customerApi.endpoints.updateGuestDetails.matchFulfilled,
      customerApi.endpoints.guestLogin.matchFulfilled,
      customerApi.endpoints.login.matchFulfilled,
      customerApi.endpoints.validate2FA.matchFulfilled,
      customerApi.endpoints.authenticateBasket.matchFulfilled,
      customerApi.endpoints.registerUser.matchFulfilled,
      customerApi.endpoints.updateCustomer.matchFulfilled,
      customerApi.endpoints.updateGuestDetails.matchFulfilled,
      customerApi.endpoints.mobileUpdate.matchFulfilled
    ].forEach(match => {
      builder.addMatcher(
        match,
        (state, { payload }) => {
          if (payload?.status === 'OK') {
            updateSignedInBasketUser(state, payload.basket);
          }
        },
      );
    });
```

I'm using jest / enzyme.

Any help would be greatly appreciated

**Comment by markerikson** [comment]
My _first_ observation is that, unrelated to the actual error, you should be using RTK's `configureStore` API instead of the legacy core `createStore` API.

The actual error here is most likely some kind of a circular import issue that's causing the `customerApi` import to be undefined (or possibly some kind of typo).

**Comment by EskiMojo14** [comment]
also unrelated to the error, but have you considered using [https://redux-toolkit.js.org/api/matching-utilities#isanyof](isAnyOf) to only need to call addMatcher once?

**Comment by matthewvero** [comment]
@EskiMojo14 Thanks! I hadn't realised we could do this, I've now implemented it.
@markerikson I've switched to the new method thanks, I also changed my imports in the slices to import the endpoints from the api, which got me closer but I now have the issue of some endpoints not being present in the object, I can't work out why as they're injected exactly the same way as the other endpoints which do seem to be present in the api at this point. 

```
TypeError: Cannot read property 'matchFulfilled' of undefined

       96 |   extraReducers: (builder) => {
       97 |     builder.addMatcher(
    >  98 |       api.endpoints.getApplicationState.matchFulfilled,
          |                                         ^
       99 |       (state, { payload }) => {
      100 |         if (payload?.basket?.status === 'OK') {
      101 |           updateSignedInBasketUser(state, payload.basket.basket);
```
The origin of the effected endpoint is this: 
```import { api } from './api';

export const applicationApi = api.injectEndpoints({
  endpoints: (builder) => ({
    getApplicationState: builder.query({
      query: (restaurantId) => restaurantId ? `application/${restaurantId}` : 'application',
    }),
  }),
  overrideExisting: false,
});

export const {
  useLazyGetApplicationStateQuery,
} = applicationApi;```

Is there something I'm missing?

**Comment by markerikson** [comment]
@matthewvero : Not sure what's going on without being able to see an actual reproduction.  My guess is still some kind of an import timing issue.  Could you put together a CodeSandbox, a Github repo, or a Replay ( https://replay.io/record-bugs ) that shows this happening?
