### ISSUE TITLE
Error when trying to use the codemod for createReducer/extraReducers

### ISSUE THREAD

**Issue by einarq** [reduxjs/redux-toolkit#2975]
I get a bunch of these errors when running the codemod, Tried installing core-js globally, but that didnt help.

Error: Cannot find module 'core-js/modules/es.array.slice.js'
Require stack:
- C:\Users\einarq\AppData\Roaming\npm-cache\_npx\13176\node_modules\@reduxjs\rtk-codemods\transforms\createReducerBuilder\index.ts
- C:\Users\einarq\AppData\Roaming\npm-cache\_npx\13176\node_modules\@reduxjs\rtk-codemods\node_modules\jscodeshift\src\Worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\Users\einarq\AppData\Roaming\npm-cache\_npx\13176\node_modules\@reduxjs\rtk-codemods\transforms\createReducerBuilder\index.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (C:\Users\einarq\AppData\Roaming\npm-cache\_npx\13176\node_modules\@reduxjs\rtk-codemods\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .ts] (C:\Users\einarq\AppData\Roaming\npm-cache\_npx\13176\node_modules\@reduxjs\rtk-codemods\node_modules\pirates\lib\index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at setup (C:\Users\einarq\AppData\Roaming\npm-cache\_npx\13176\node_modules\@reduxjs\rtk-codemods\node_modules\jscodeshift\src\Worker.js:91:18)
    at Object.<anonymous> (C:\Users\einarq\AppData\Roaming\npm-cache\_npx\13176\node_modules\@reduxjs\rtk-codemods\node_modules\jscodeshift\src\Worker.js:45:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\einarq\\AppData\\Roaming\\npm-cache\\_npx\\13176\\node_modules\\@reduxjs\\rtk-codemods\\transforms\\createReducerBuilder\\index.ts',
    'C:\\Users\\einarq\\AppData\\Roaming\\npm-cache\\_npx\\13176\\node_modules\\@reduxjs\\rtk-codemods\\node_modules\\jscodeshift\\src\\Worker.js'
  ]
}

![image](https://user-images.githubusercontent.com/212751/205599135-f9e4d3d6-0ad6-40c6-b4b0-bb5d40e136cd.png)

**Comment by markerikson** [comment]
Huh. Honestly, no idea what's going on there.  That all looks like `npm` or `npx`-related stuff, and that's totally out of our control.

**Comment by einarq** [comment]
Ok. Using git bash on windows, npm 8. Not sure if that might be related.
