### ISSUE TITLE
RangeError: Maximum call stack size exceeded after upgrading to `v1.9.1` from `v1.8.6`

### ISSUE THREAD

**Issue by kushagra010** [reduxjs/redux-toolkit#3023]
Getting the below error after upgrading to `v1.9.1` from `v1.8.6`. There is no issue if on `v1.8.6`.
```
[RangeError: Maximum call stack size exceeded]
 WARN  Possible Unhandled Promise Rejection (id: 0):
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:161080:60)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:161394:17)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162464:61)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162321:61)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    ... skipping 1895 frames
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at queueMicrotask (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27711:68)
    at then (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:162326:79)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:112359:47)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/6f4q4b2q/x86/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/6f4q4b2q/x86/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27489:26)
    at _callTimer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27404:17)
    at _callReactNativeMicrotasksPass (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27437:17)
    at callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:27601:44)
    at __callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:20844:46)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:20644:45)
    at __guard (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:20824:15)
    at flushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:20643:21)
    at invokeCallbackAndReturnFlushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativebasetemplate&modulesOnly=false&runModule=true:20637:33)
```
    
package.json
```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/checkbox": "^0.5.14",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@reduxjs/toolkit": "^1.9.1",     <-----------------------
    "@types/lodash.get": "^4.4.7",
    "lodash.get": "^4.4.2",
    "react": "18.1.0",
    "react-native": "0.70.2",
    "react-native-dotenv": "^3.3.1",
    "react-native-icomoon": "^0.1.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-snackbar": "^2.4.0",
    "react-native-svg": "^13.6.0",
    "react-redux": "^8.0.4",
    "redux-persist": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@storybook/addon-actions": "^5.3",
    "@storybook/addon-knobs": "^5.3",
    "@storybook/addon-links": "^5.3",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.26",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.70.4",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.41.0",
    "@typescript-eslint/parser": "^5.41.0",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.5",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^8.26.0",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.0.0",
    "husky": "^8.0.1",
    "jest": "^26.6.3",
    "lint-staged": "^13.0.3",
    "metro-react-native-babel-preset": "0.72.3",
    "prettier": "^2.7.1",
    "react-dom": "18.1.0",
    "react-native-dotenv": "^3.3.1",
    "react-native-storybook-loader": "^2.0.5",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  }
  ```

**Comment by markerikson** [comment]
Unfortunately that call stack is almost completely unhelpful :(  The only thing I see that's useful in there is the reference to `queueMicrotask`, which we only call in two places: the RTKQ middleware, and the `autoBatchEnhancer`.

Can you show an actual repo that demonstrates this happening?  Is there any way to create a minimal repro of just this problem, maybe as an Expo Snack that runs on the web?

Since this appears to be RN, it's going to be _much_ harder for us to investigate this.

**Comment by kushagra010** [comment]
Sure, let me check if I can reproduce it on Expo Snack. Thanks for the quick response.

**Comment by kushagra010** [comment]
@markerikson Here's the [repo](https://github.com/kushagra010/RNApp) for issue reproduction.
Currently `reduxjs/toolkit` version is set to `1.9.1` which is breaking. But changing it to `1.8.6` works.

**Comment by markerikson** [comment]
@kushagra010 Nope, sorry. Haven't had time to look at this.

**Comment by Mywbj** [comment]
> @kushagra010不，谢谢。没时间看这个。

I also encountered this problem. Object a can no longer nest object a。

**Comment by AtoianAvetik** [comment]
I'm currently upgrading project to latest versions of packages like react 17 -> 18, react native 0.68 -> 0.71, expo 46 -> 48, etc. and spent almost HALF OF DAY to find where this `Maximum call stack size...` issue is comes from!!
Thx to [kushagra010](https://github.com/kushagra010), downgrading to version 1.8.6 helps and everything is working like a sharm with latest versions of all packages...except redux-toolkit -_-

**Comment by markerikson** [comment]
@AtoianAvetik downgrading isn't an "answer", it's a workaround.

Out of curiosity, what happens if you use the latest RTK 2.0 alphas instead?

**Comment by AtoianAvetik** [comment]
@markerikson Hi! Thx for answer, yep, I'm agree with you that this is just workaround.
About RTK 2.0, I didn't test it since our team policy restricts developers from using unstable versions of any packages.
Later, once current upgrade process will be done, I will check :)

**Comment by kushagra51** [comment]
@markerikson I checked on RTK's `2.0.0-alpha.5` version. And it is still breaking with the same error. You can reproduce the issue by bumping the version to `2.0.0-alpha.5` in the repo mentioned [here](https://github.com/reduxjs/redux-toolkit/issues/3023#issuecomment-1363979590)

**Comment by kushagra010** [comment]
@markerikson I checked on RTK's 2.0.0-alpha.5 version. And it is still breaking with the same error. You can reproduce the issue by bumping the version to 2.0.0-alpha.5 in the repo mentioned https://github.com/reduxjs/redux-toolkit/issues/3023#issuecomment-1363979590

**Comment by markerikson** [comment]
@kushagra010 Circling back to this issue:

Unfortunately I don't use RN at all, and I don't have time to try to figure out how to run RN projects locally or debug them.

Can you try converting this to an Expo Snack, or at least an Expo project with a Web target?  If so, does it happen in that environment?

**Comment by kushagra010** [comment]
@markerikson Sorry for not getting back to you sooner.

I tried creating the replica of my above (https://github.com/reduxjs/redux-toolkit/issues/3023#issuecomment-1363979590) reproduction repo in an expo project with Android target and it is working fine even on `1.9.1` and above. Here's the expo project for reference https://github.com/kushagra010/my-app

So, it seems like the issue persists in the `React Native CLI` project only.

**Comment by markerikson** [comment]
Realistically, we don't have time to go debugging into RN projects any time soon.

We did make some changes to the RTKQ internals in 2.0. Can someone please try out 2.0 and see if that fixes things?

**Comment by markerikson** [comment]
Closing as we're long past 2.0 and no one else has continued to report this.
