### ISSUE TITLE
When I query chat messages using the RTK query endpoint, I get the following error message:

### ISSUE THREAD

**Issue by ZivGit** [reduxjs/redux-toolkit#3039]
#### Issue Description

When I query chat messages using the RTK query endpoint, I get the following error message:

#### Steps to Reproduce / Code Snippets

```ts
// Channels.ts
import { FlatList } from 'react-native';

const Channels = ({ navigation }: ChannelsProps): JSX.Element => {
    const onDrawerPressHandler = (key: any, item: any) => {
        switch (key) {
            case 'LINK':
                navigation.navigate('Chat', item);
                break
            default:
                console.log({ key, item });
        }
    };

    return (
        <View style={styles.container}>
            <FlatList
                data={channels}
                refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
                renderItem={({index, item}: { index: number, item: any }) => (
                    <RowActions {...item} onDrawerPress={(key: any) => onDrawerPressHandler(key, item)} />
                )}
                keyExtractor={(item: any, index: number) => index.toString()}
                style={backgroundStyle}
            />
        </View>
    );
};
```

```ts
// Chat.ts
import { useGetMessageByChannelIdQuery } from '~services/channel';

const Chat = ({ route }: ChatProps): JSX.Element => {
    const { data: messageData, isLoading, isSuccess } = useGetMessageByChannelIdQuery(route.params._id);
    console.log(111111111, messageData)

    return (
        <View style={{ flex: 1 }}>
            {isSuccess}
        </View>
    );
};
```

```js
LOG  111111111 [{"_id": "6396f1c9580c0febcc073b1f", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-12-12T09:18:01.946Z", "text": "14", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "637ee4f3cf652cd93cebf3ac", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-11-24T03:28:51.192Z", "text": "13", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "62826a99a64c830d1b336b16", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-05-16T15:15:37.246Z", "text": "12", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "628267fea64c830d1b336b13", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-05-16T15:04:30.870Z", "text": "11", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "628265eea64c830d1b336b0f", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-05-16T14:55:42.562Z", "text": "10", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "628265aaa64c830d1b336b0e", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-05-16T14:54:34.830Z", "text": "9", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "62826521a64c830d1b336b0c", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-05-16T14:52:17.826Z", "text": "8", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "626e7a16addadb177db77b55", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-05-01T12:16:22.454Z", "text": "7", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "626e4ba7addadb177db77b4d", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-05-01T08:58:15.220Z", "text": "6", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "626d2456acdc783066749dc9", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-04-30T11:58:14.347Z", "text": "5", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "626d244dacdc783066749dc8", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-04-30T11:58:05.538Z", "text": "4", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "626d244bacdc783066749dc7", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-04-30T11:58:03.036Z", "text": "3", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "626d2441acdc783066749dc6", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-04-30T11:57:53.970Z", "text": "2", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}, {"_id": "626d243facdc783066749dc5", "channelId": "60d402b22880b33b23b5d99c", "createdAt": "2022-04-30T11:57:51.321Z", "text": "1", "user": {"_id": "60c876ea6e3b4125c3046432", "avatar": "https://dummyimage.com/200x200/00E67D/000.jpg&text=Zoe", "name": "Zoe"}}] 
    at Chat (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:199806:21)
    at StaticContainer (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:212887:17)
    at EnsureSingleNavigator (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:208366:24)
    at SceneView (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:212792:22)
    at RCTView
    at View
    at RCTView
    at View
    at RCTView
    at View
    at CardSheet (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:219738:23)
    at RCTView
    at View
    at AnimatedComponent (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:95617:38)
    at AnimatedComponentWrapper
    at PanGestureHandler (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:113283:38)
    at PanGestureHandler (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:219819:34)
    at RCTView
    at View
    at AnimatedComponent (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:95617:38)
    at AnimatedComponentWrapper
    at RCTView
    at View
    at Card (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:219166:36)
    at CardContainer (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:218760:34)
    at RNSScreen
    at AnimatedComponent (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:95617:38)
    at AnimatedComponentWrapper
    at Suspender (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:220402:22)
    at Suspense
    at Freeze (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:220424:23)
    at DelayedFreeze (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:220024:22)
    at InnerScreen (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:220078:36)
    at Screen (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:220273:36)
    at MaybeScreen (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:219888:24)
    at RNSScreenContainer
    at ScreenContainer (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:220199:31)
    at MaybeScreenContainer (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:219873:23)
    at RCTView
    at View
    at Background (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:207225:21)
    at CardStack (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:217878:36)
    at RCTView
    at View
    at SafeAreaProviderCompat (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:215841:25)
    at RCTView
    at View
    at GestureHandlerRootView
    at StackView (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:216939:36)
    at PreventRemoveProvider (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:211725:25)
    at NavigationContent (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:212574:22)
    at anonymous (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:212588:27)
    at StackNavigator (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:216796:18)
    at EnsureSingleNavigator (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:208366:24)
    at BaseNavigationContainer (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:207915:28)
    at ThemeProvider (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:214216:21)
    at NavigationContainerInner (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:214092:26)
    at RNCSafeAreaProvider
    at SafeAreaProvider (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:173321:24)
    at RCTView
    at View
    at GestureHandlerRootView
    at App (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:173005:87)
    at ThemeProvider (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:176730:38)
    at RCTView
    at View
    at Portal.Host (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:185378:36)
    at Provider (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:176955:41)
    at PersistGate (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:220911:22)
    at Provider (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:158310:21)
    at Root
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:102930:36)
    at App(RootComponent) (http://192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp:108725:28)
Error: ENOENT: no such file or directory, open '/Users/zhangmengmin/Documents/ReactNative/App/http:/192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (/Users/zhangmengmin/Documents/ReactNative/App/node_modules/metro/src/Server.js:1028:18)
    at Server._symbolicate (/Users/zhangmengmin/Documents/ReactNative/App/node_modules/metro/src/Server.js:1101:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (/Users/zhangmengmin/Documents/ReactNative/App/node_modules/metro/src/Server.js:458:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/zhangmengmin/Documents/ReactNative/App/http:/192.168.0.215:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.develop.RNApp'
}
```

#### Expected Results

No error message

#### Additional Information

* Nodejs version: v16.17.1
* React version: v18.1.0
* React Native version: v0.70.1
* react-native-gifted-chat version: ^1.0.4
* Platform(s) (iOS, Android, or both?): iOS 16.2
* TypeScript version: ^4.8.3

**Comment by ZivGit** [comment]
The error message is determined to be caused by console.error()
