### ISSUE TITLE
ReferenceError: AbortController is not defined

### ISSUE THREAD

**Issue by dansimau** [reduxjs/redux-toolkit#3171]
```
$ node --version
v18.14.0
```

```js
// jest.config.js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
};
```

```js
// package.json
{
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.2",
    "@types/jest": "^26",
    "jest": "^26",
    "ts-jest": "^26",
    "typescript": "^4.9.5"
  }
}
```

```ts
// redux.test.js
import { configureStore, createListenerMiddleware } from '@reduxjs/toolkit';

describe('redux middleware', () => {
  test('that it works', async () => {
    let itWorks = false;

    const reducer = () => {
      console.log('Congratulations! Your reducer ran.');
    };

    const listenerMiddleware = createListenerMiddleware();

    listenerMiddleware.startListening({
      predicate: () => true, // always run the middleware
      effect: async () => {
        console.log('Wow, this actually works!');
        itWorks = true;
      },
    });

    const store = configureStore({ reducer, middleware: [listenerMiddleware.middleware] });

    store.dispatch({ type: 'fakeAction' });

    await (async () => true)();

    expect(itWorks).toEqual(true);
  });
});
```

When running this test, I get:

```
$ ./node_modules/.bin/jest ./redux.test.ts --no-cache

 RUNS  ./redux.test.ts
/Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:1828
                    internalTaskController = new AbortController();
                    ^

ReferenceError: AbortController is not defined
    at /Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/src/listenerMiddleware/index.ts:374:11
    at step (/Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:38:23)
    at Object.next (/Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:19:53)
    at /Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:112:65
    at new Promise (<anonymous>)
    at __async (/Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:94:12)
    at notifyListener (/Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/src/listenerMiddleware/index.ts:373:8)
    at Object.dispatch (/Volumes/Code/redux-jest-test-26/node_modules/@reduxjs/toolkit/src/listenerMiddleware/index.ts:484:13)
    at /Volumes/Code/redux-jest-test-26/redux.test.ts:23:11
    at step (/Volumes/Code/redux-jest-test-26/redux.test.ts:33:23)

Node.js v18.14.0
```

**Comment by markerikson** [comment]
Not sure what to tell you. If I just start Node and check in the REPL, `AbortController` exists:

```
$ node
Welcome to Node.js v18.11.0.
Type ".help" for more information.
> typeof AbortController
'function'
```

There's nothing special that RTK does here.  Check your own environment and see if `AbortController` exists, I guess?

**Comment by dansimau** [comment]
```
$ node
Welcome to Node.js v18.14.0.
Type ".help" for more information.
> AbortController
[class AbortController]
>
```

@markerikson did you try to reproduce this using the code above?

I can reproduce it on two machines and a codesandbox.

Here is a repo for easy cloning:
https://gist.github.com/dansimau/8a266760a25e91950bfab1aa21304a26

**Comment by markerikson** [comment]
@dansimau : does this happen when the code actually _runs_?  Or just in Jest + `environment: "node"`?

My point is that RTK truly does not do anything odd here.  We just reference `AbortController`, expecting it to exist.

**Comment by dansimau** [comment]
Gotcha, yes I can confirm it only happens in the jest environment.

Thanks and sorry for the trouble.
