### ISSUE TITLE
Unit test with vitest and msw fails with message about AbortSignal

### ISSUE THREAD

**Issue by Symbitic** [reduxjs/redux-toolkit#3590]
A unit test I have that uses vitest, msw, and redux-toolkit (RTK) gives this error:

```
An unhandled error occurred processing a request for the endpoint "getDetails".
In the case of an unhandled error, no tags will be "provided" or "invalidated". TypeError: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
    at new NodeError (node:internal/errors:399:5)
    at getEventListeners (node:events:914:9)
    at new Request (node:internal/deps/undici/undici:7138:17)
    at Proxy.<anonymous> (C:\Users\me\app\node_modules\@reduxjs\toolkit\src\query\fetchBaseQuery.ts:268:21)
    at step (C:\Users\me\app\node_modules\@reduxjs\toolkit\dist\query\rtk-query.cjs.development.js:23:23)
    at Object.next (C:\Users\me\app\node_modules\@reduxjs\toolkit\dist\query\rtk-query.cjs.development.js:4:53)
    at fulfilled (C:\Users\me\app\node_modules\@reduxjs\toolkit\dist\query\rtk-query.cjs.development.js:95:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Test file:

```tsx
import React, { useEffect } from "react";
import { Provider } from "react-redux";
import { describe, expect, it } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import { store } from "../store";
import { useGetDetailsQuery } from "./DetailsService";

function GetDetailsApp() {
    const { data, error, isError, isLoading } = useGetDetailsQuery({
        id: 1
    });
    if (isLoading) {
        return <h1>Loading</h1>;
    }
    if (isError) {
        return <h1>Error: {error["message"]}</h1>;
    }
    return (
        <ul>
            <li>ID = {data.id}</li>
            <li>Name = {data.name}</li>
            <li>Finished</li>
        </ul>
    );
}

describe("detailsAPI", () => {
    it("should return details for an ID", async () => {
        renderCustom(
            <Provider store={store}>
                <GetDetailsApp />
            </Provider>
        );
        expect(screen.getByText("Loading")).toBeDefined();

        await waitFor(() => screen.getByText(/Finished/i));
        expect(screen.getByText("ID = 1")).toBeDefined();
        expect(screen.getByText("Name = Test")).toBeDefined();
    });
});
```

RTK Service:

```ts
export interface IGetDetailsRequest {
    id: number;
}

export interface IGetDetailsResponse {
    id: number;
    name: string;
}

export const detailsAPI = createApi({
    reducerPath: "detailsAPI",
    baseQuery: fetchBaseQuery({
        baseUrl: import.meta.env.VITE_API_URL,
    }),
    endpoints: (builder) => ({
        getDetails: builder.query<
            IGetDetailsResponse,
            IGetDetailsRequest
        >({
            query: ({ id }) => {
                return {
                    url: "GetDetails",
                    method: "POST",
                    body: {
                        id: id
                    },
                };
            },
            transformResponse: (response) => {
                if (!response) {
                    return undefined;
                }
                return response.data;
            },
        }),
    }),
});

export const { useGetDetailsQuery } = detailsAPI;
```

Vitest setup file:

```ts
import { rest } from "msw";
import { setupServer } from "msw/node";
import { beforeAll, expect, vi } from "vitest";

const BASE_URL = import.meta.env.VITE_API_URL;

const handlers = [
    rest.all(
        `${BASE_URL}GetDetails`,
        (_req, res, ctx) => {
            const body = {
                data: {
                    id: 1,
                    name: "Test"
                },
                isSuccess: true,
            };
            return res(ctx.status(200), ctx.json(body));
        }
    ),
];

export const server = setupServer(...handlers);
beforeAll(() => {
    server.listen({ onUnhandledRequest: "error" });
});
afterAll(() => {
    server.close();
});
afterEach(() => server.resetHandlers());
```

**Comment by phryneas** [comment]
It seems like the `fetch` version and `AbortController` version you have in that environment are not compatible with each other. There is probably some incorrect polyfill in play somewhere.

**Comment by LuanScudeler** [comment]
Same as https://github.com/reduxjs/redux-toolkit/issues/3254
