### ISSUE TITLE
Error: path parameter path does not seem to be defined

### ISSUE THREAD

**Issue by kahirokunn** [reduxjs/redux-toolkit#3723]
```ts
import type { ConfigFile } from '@rtk-query/codegen-openapi'

const config: ConfigFile = {
  schemaFile:
    'https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json',
  apiFile: './emptyApi.ts',
  apiImport: 'emptySplitApi',
  outputFile: './k8sApi.ts',
  exportName: 'k8sApi',
}

export default config
```

I tried adding k8s swagger and got an error!

```sh
└─> npx @rtk-query/codegen-openapi openapi-config.ts
Generating ./k8sApi.ts
Error: path parameter path does not seem to be defined in '/api/v1/namespaces/{namespace}/pods/{name}/proxy/{path}'!
    at /example/node_modules/@rtk-query/codegen-openapi/src/generate.ts:467:13
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at generatePathExpression (/example/node_modules/@rtk-query/codegen-openapi/src/generate.ts:464:21)
    at generateQueryFn (/example/node_modules/@rtk-query/codegen-openapi/src/generate.ts:413:15)
    at generateEndpoint (/example/node_modules/@rtk-query/codegen-openapi/src/generate.ts:343:16)
    at /example/node_modules/@rtk-query/codegen-openapi/src/generate.ts:144:15
    at Array.map (<anonymous>)
    at generateApi (/example/node_modules/@rtk-query/codegen-openapi/src/generate.ts:143:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

There is an error in the following section.

```ts
function generatePathExpression(
  path: string,
  pathParameters: QueryArgDefinition[],
  rootObject: ts.Identifier,
  isFlatArg: boolean
) {
  const expressions: Array<[string, string]> = [];

  const head = path.replace(/\{(.*?)\}(.*?)(?=\{|$)/g, (_, expression, literal) => {
    const param = pathParameters.find((p) => p.originalName === expression);
    if (!param) {
      throw new Error(`path parameter ${expression} does not seem to be defined in '${path}'!`);
    }
    expressions.push([param.name, literal]);
    return '';
  });

  return expressions.length
    ? factory.createTemplateExpression(
        factory.createTemplateHead(head),
        expressions.map(([prop, literal], index) =>
          factory.createTemplateSpan(
            isFlatArg ? rootObject : accessProperty(rootObject, prop),
            index === expressions.length - 1
              ? factory.createTemplateTail(literal)
              : factory.createTemplateMiddle(literal)
          )
        )
      )
    : factory.createNoSubstitutionTemplateLiteral(head);
}
```

**Comment by kahirokunn** [comment]
How about making everything a string required if there is no pah parameter?

**Comment by kahirokunn** [comment]
I was feeding openapi v2.
