### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')

### ISSUE THREAD

**Issue by hornta** [reduxjs/redux-toolkit#3726]
### User Error! Not a bug!

Hello! I just got this error after converting our very large createApi file to multiple files using injectEndpoints. I can't seem to figure out why this happens, do you have any idea?

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at buildSlice.ts:179:26
    at updateQuerySubstateIfExists (buildSlice.ts:53:5)
    at buildSlice.ts:169:11
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at combination (redux.js:560:29)
```

I've made a replay recording but for some reason it didn't get the console output despite I could see the error being logged to the console, so I'm posting an image of the console error.

https://app.replay.io/recording/prognosjuni-konsult-2023-09-05-091335-exopen--e9c31c16-48b5-411a-a4f0-839d649049bc

![image](https://github.com/reduxjs/redux-toolkit/assets/4553604/ffce3fe6-c27b-42db-ab5f-599723ec6bd1)

**Comment by markerikson** [comment]
Looks like the replay isn't public - can you share it?

**Comment by hornta** [comment]
> Looks like the replay isn't public - can you share it?

I think it's public now

**Comment by hornta** [comment]
I could extract some more information on this error now.

I put a conditional breakpoint at the line that errors. It seems to expect `definitions` to have `getHolidays` key but `getHolidays` is an endpoint I've moved out from the file and it being injected into the original createApi definition. I hope this is enough for you to go on.

![image](https://github.com/reduxjs/redux-toolkit/assets/4553604/b5028a12-60f9-4417-a70f-3f20bec6b00e)

```
buildSlice.ts:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at buildSlice.ts:179:26
    at updateQuerySubstateIfExists (buildSlice.ts:53:5)
    at buildSlice.ts:169:11
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at combination (redux.js:560:29)
(anonymous) @ buildSlice.ts:179
updateQuerySubstateIfExists @ buildSlice.ts:53
(anonymous) @ buildSlice.ts:169
(anonymous) @ createReducer.ts:294
produce @ immerClass.ts:94
(anonymous) @ createReducer.ts:293
reducer @ createReducer.ts:260
reducer @ createSlice.ts:372
combination @ redux.js:560
reducer @ buildSlice.ts:492
combination @ redux.js:560
hu @ VM10815:3
yu @ VM10815:3
(anonymous) @ VM10815:3
dispatch @ redux.js:288
s @ VM10815:3
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ redux.js:691
(anonymous) @ createAsyncThunk.ts:682
step @ state_adapter.ts:1
(anonymous) @ state_adapter.ts:1
fulfilled @ state_adapter.ts:1
Promise.then (async)
(anonymous) @ buildInitiate.ts:425
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10815:6
(anonymous) @ buildHooks.ts:768
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
buildSlice.ts:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at buildSlice.ts:179:26
    at updateQuerySubstateIfExists (buildSlice.ts:53:5)
    at buildSlice.ts:169:11
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at combination (redux.js:560:29)
(anonymous) @ buildSlice.ts:179
updateQuerySubstateIfExists @ buildSlice.ts:53
(anonymous) @ buildSlice.ts:169
(anonymous) @ createReducer.ts:294
produce @ immerClass.ts:94
(anonymous) @ createReducer.ts:293
reducer @ createReducer.ts:260
reducer @ createSlice.ts:372
combination @ redux.js:560
reducer @ buildSlice.ts:492
combination @ redux.js:560
hu @ VM10815:3
yu @ VM10815:3
(anonymous) @ VM10815:3
dispatch @ redux.js:288
s @ VM10815:3
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ redux.js:691
(anonymous) @ createAsyncThunk.ts:682
step @ state_adapter.ts:1
(anonymous) @ state_adapter.ts:1
fulfilled @ state_adapter.ts:1
Promise.then (async)
(anonymous) @ buildInitiate.ts:377
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10815:6
(anonymous) @ buildHooks.ts:768
commitHookEffectListMount @ react-dom.development.js:23150
invokePassiveEffectMountInDEV @ react-dom.development.js:25154
invokeEffectsInDev @ react-dom.development.js:27351
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:27330
flushPassiveEffectsImpl @ react-dom.development.js:27056
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
buildSlice.ts:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at buildSlice.ts:179:26
    at updateQuerySubstateIfExists (buildSlice.ts:53:5)
    at buildSlice.ts:169:11
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at combination (redux.js:560:29)
(anonymous) @ buildSlice.ts:179
updateQuerySubstateIfExists @ buildSlice.ts:53
(anonymous) @ buildSlice.ts:169
(anonymous) @ createReducer.ts:294
produce @ immerClass.ts:94
(anonymous) @ createReducer.ts:293
reducer @ createReducer.ts:260
reducer @ createSlice.ts:372
combination @ redux.js:560
reducer @ buildSlice.ts:492
combination @ redux.js:560
hu @ VM10815:3
yu @ VM10815:3
(anonymous) @ VM10815:3
dispatch @ redux.js:288
s @ VM10815:3
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ redux.js:691
(anonymous) @ createAsyncThunk.ts:682
step @ state_adapter.ts:1
(anonymous) @ state_adapter.ts:1
fulfilled @ state_adapter.ts:1
Promise.then (async)
(anonymous) @ buildInitiate.ts:425
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10815:6
(anonymous) @ buildHooks.ts:768
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
buildSlice.ts:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at buildSlice.ts:179:26
    at updateQuerySubstateIfExists (buildSlice.ts:53:5)
    at buildSlice.ts:169:11
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at combination (redux.js:560:29)
(anonymous) @ buildSlice.ts:179
updateQuerySubstateIfExists @ buildSlice.ts:53
(anonymous) @ buildSlice.ts:169
(anonymous) @ createReducer.ts:294
produce @ immerClass.ts:94
(anonymous) @ createReducer.ts:293
reducer @ createReducer.ts:260
reducer @ createSlice.ts:372
combination @ redux.js:560
reducer @ buildSlice.ts:492
combination @ redux.js:560
hu @ VM10815:3
yu @ VM10815:3
(anonymous) @ VM10815:3
dispatch @ redux.js:288
s @ VM10815:3
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ redux.js:691
(anonymous) @ createAsyncThunk.ts:682
step @ state_adapter.ts:1
(anonymous) @ state_adapter.ts:1
fulfilled @ state_adapter.ts:1
Promise.then (async)
(anonymous) @ buildInitiate.ts:377
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10815:6
(anonymous) @ buildHooks.ts:768
commitHookEffectListMount @ react-dom.development.js:23150
invokePassiveEffectMountInDEV @ react-dom.development.js:25154
invokeEffectsInDev @ react-dom.development.js:27351
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:27330
flushPassiveEffectsImpl @ react-dom.development.js:27056
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
buildSlice.ts:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at buildSlice.ts:179:26
    at updateQuerySubstateIfExists (buildSlice.ts:53:5)
    at buildSlice.ts:169:11
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at combination (redux.js:560:29)
(anonymous) @ buildSlice.ts:179
updateQuerySubstateIfExists @ buildSlice.ts:53
(anonymous) @ buildSlice.ts:169
(anonymous) @ createReducer.ts:294
produce @ immerClass.ts:94
(anonymous) @ createReducer.ts:293
reducer @ createReducer.ts:260
reducer @ createSlice.ts:372
combination @ redux.js:560
reducer @ buildSlice.ts:492
combination @ redux.js:560
hu @ VM10815:3
yu @ VM10815:3
(anonymous) @ VM10815:3
dispatch @ redux.js:288
s @ VM10815:3
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ redux.js:691
(anonymous) @ createAsyncThunk.ts:682
step @ state_adapter.ts:1
(anonymous) @ state_adapter.ts:1
fulfilled @ state_adapter.ts:1
Promise.then (async)
(anonymous) @ buildInitiate.ts:425
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10815:6
(anonymous) @ buildHooks.ts:768
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
buildSlice.ts:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'merge')
    at buildSlice.ts:179:26
    at updateQuerySubstateIfExists (buildSlice.ts:53:5)
    at buildSlice.ts:169:11
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at combination (redux.js:560:29)
(anonymous) @ buildSlice.ts:179
updateQuerySubstateIfExists @ buildSlice.ts:53
(anonymous) @ buildSlice.ts:169
(anonymous) @ createReducer.ts:294
produce @ immerClass.ts:94
(anonymous) @ createReducer.ts:293
reducer @ createReducer.ts:260
reducer @ createSlice.ts:372
combination @ redux.js:560
reducer @ buildSlice.ts:492
combination @ redux.js:560
hu @ VM10815:3
yu @ VM10815:3
(anonymous) @ VM10815:3
dispatch @ redux.js:288
s @ VM10815:3
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.ts:102
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ redux.js:691
(anonymous) @ createAsyncThunk.ts:682
step @ state_adapter.ts:1
(anonymous) @ state_adapter.ts:1
fulfilled @ state_adapter.ts:1
Promise.then (async)
(anonymous) @ buildInitiate.ts:377
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
dispatch @ VM10815:6
(anonymous) @ buildHooks.ts:768
commitHookEffectListMount @ react-dom.development.js:23150
invokePassiveEffectMountInDEV @ react-dom.development.js:25154
invokeEffectsInDev @ react-dom.development.js:27351
commitDoubleInvokeEffectsInDEV @ react-dom.development.js:27330
flushPassiveEffectsImpl @ react-dom.development.js:27056
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

`emptyPlanningApi` is the `createApi`.
```ts
const extendedApi = emptyPlanningApi.injectEndpoints({
  endpoints: (builder) => ({
    getHolidays: builder.query<
      DomainHoliday[],
      { companyDomainId: string; planId: string }
    >({
      query({ companyDomainId, planId }) {
        return `/v1/${companyDomainId}/plans/${planId}/holidays`;
      },
      providesTags(result) {
        return result
          ? [
              "Holiday",
              ...result.map((result) => ({
                type: "Holiday" as const,
                id: result.id,
              })),
            ]
          : ["Holiday"];
      },
    }),

    addHoliday: builder.mutation<
      void,
      {
        description: string | null;
        date: string;
        companyDomainId: string;
        planId: string;
      }
    >({
      query({ companyDomainId, planId, date, description }) {
        return {
          method: "POST",
          url: `/v1/${companyDomainId}/plans/${planId}/holidays`,
          body: { date, description },
        };
      },
      invalidatesTags() {
        return ["Holiday"];
      },
    }),

    updateHoliday: builder.mutation<
      void,
      {
        description: string | null;
        date: string;
        companyDomainId: string;
        planId: string;
        holidayId: string;
      }
    >({
      query({ companyDomainId, planId, date, description, holidayId }) {
        return {
          method: "PUT",
          url: `/v1/${companyDomainId}/plans/${planId}/holidays/${holidayId}`,
          body: { date, description },
        };
      },
      invalidatesTags(result, error, arg) {
        if (error) {
          return ["Holiday"];
        } else {
          return [{ type: "Holiday", id: arg.holidayId }];
        }
      },
    }),

    removeHoliday: builder.mutation<
      void,
      {
        companyDomainId: string;
        planId: string;
        holidayId: string;
      }
    >({
      query({ companyDomainId, planId, holidayId }) {
        return {
          method: "DELETE",
          url: `/v1/${companyDomainId}/plans/${planId}/holidays/${holidayId}`,
        };
      },
      invalidatesTags(result, error, arg) {
        if (error) {
          return ["Holiday"];
        } else {
          return [{ type: "Holiday", id: arg.holidayId }];
        }
      },
    }),

    setDefaultHolidays: builder.mutation<
      void,
      {
        companyDomainId: string;
        planId: string;
      }
    >({
      query({ companyDomainId, planId }) {
        return {
          method: "POST",
          url: `/v1/${companyDomainId}/plans/${planId}/holidays/defaults`,
        };
      },
      invalidatesTags() {
        return ["Holiday"];
      },
    }),
  }),
  overrideExisting: false,
});

export const {
  useAddHolidayMutation,
  useGetHolidaysQuery,
  useRemoveHolidayMutation,
  useSetDefaultHolidaysMutation,
  useUpdateHolidayMutation,
} = extendedApi;

```

**Comment by hornta** [comment]
Sorry this is not a bug, I was adding the incorrect api slice to my redux store. I was adding the result of injectEndpoints instead of the one created from createApi

**Comment by markerikson** [comment]
Gotcha.
