### ISSUE TITLE
[RTK Query Codegen OpenAPI] circular reference handling

### ISSUE THREAD

**Issue by kristapsstrals** [reduxjs/redux-toolkit#3827]
Running codegen with a model that references itself causes a call stack exception

example C# model:
```cs
public class TestDto
{
    public int Id { get; set; } 
    public List<TestDto> LinkedDocuments { get; set;}
}
```

generated OpenAPI json spec:
openapi_error.json
```json
{
  "openapi": "3.0.1",
  "info": {
      "title": "Test API",
      "description": "Test API",
      "version": "1.0.0"
  },
  "servers": [
      {
          "url": "http://localhost:7109/api"
      }
  ],
  "paths": {
      "/test": {
          "get": {
              "tags": [
                  "test"
              ],
              "summary": "Test recursion",
              "description": "Test recursion",
              "operationId": "Test",
              "responses": {
                  "200": {
                      "description": "Payload of Array of TestDto",
                      "content": {
                          "application/json": {
                              "schema": {
                                  "type": "array",
                                  "items": {
                                      "$ref": "#/components/schemas/testDto"
                                  }
                              }
                          }
                      }
                  }
              },
              "x-ms-visibility": "important"
          }
      }
  },
  "components": {
      "schemas": {
          "testDto": {
              "type": "object",
              "properties": {
                  "id": {
                      "type": "integer",
                      "format": "int32"
                  },
                  "linkedDocuments": {
                      "type": "array",
                      "items": {
                          "$ref": "#/components/schemas/testDto"
                      }
                  }
              }
          }
      },
      "securitySchemes": {
      }
  }
}
```

openapi-config_error.ts:
```ts
import type { ConfigFile } from '@rtk-query/codegen-openapi'

const config: ConfigFile = {
  schemaFile: './openapi_error.json',
  apiFile: './src/redux/services/api.empty.ts',
  apiImport: 'emptySplitApi',
  exportName: 'testApi',
  hooks: {
    lazyQueries: true,
    mutations: true,
    queries: true
  },
  outputFile: './src/redux/services/testApi.ts',
}

export default config
```

## Expect

Api definition generated successfully, type looks something like this:

```ts
type TestDto = {
  id?: number,
  linkedDocuments?: TestDto[]
}
```

## Actual result:

```
npx @rtk-query/codegen-openapi openapi-config_error.ts

Generating ./src/redux/services/testApi.ts
RangeError: Maximum call stack size exceeded
    at get global [as global] (<anonymous>)
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at C:\git\standarddigital\authoring\authoring-frontend-react\node_modules\oazapfts\src\codegen\generate.ts:129:29
    at Array.map (<anonymous>)
    at refPathToPropertyPath (C:\git\standarddigital\authoring\authoring-frontend-react\node_modules\oazapfts\src\codegen\generate.ts:129:6)
    at ApiGenerator.resolve (C:\git\standarddigital\authoring\authoring-frontend-react\node_modules\oazapfts\src\codegen\generate.ts:322:18)
    at ApiGenerator.checkSchemaOnlyMode (C:\git\standarddigital\authoring\authoring-frontend-react\node_modules\oazapfts\src\codegen\generate.ts:781:41)
    at ApiGenerator.checkSchemaOnlyMode (C:\git\standarddigital\authoring\authoring-frontend-react\node_modules\oazapfts\src\codegen\generate.ts:794:16)
    at C:\git\standarddigital\authoring\authoring-frontend-react\node_modules\oazapfts\src\codegen\generate.ts:808:14
```

## Remarks

This should work fine since the circular property `linkedDocuments` can be undefined or an empty array.
Swagger UI handles the OpenAPI definition just fine
https://editor.swagger.io/

![image](https://github.com/reduxjs/redux-toolkit/assets/26419290/cef0f8c2-2d8d-4c7b-8547-3bf459593ddc)

**Comment by TomasSestak** [comment]
Same here

**Comment by markerikson** [comment]
Per the stack trace, this is actually an error in the upstream `oazapfts` library. Could you file the issue over there? Thanks!

**Comment by kristapsstrals** [comment]
> Per the stack trace, this is actually an error in the upstream `oazapfts` library. Could you file the issue over there? Thanks!

You're correct, thanks for the info. Checked their repo and found that there is already a ticket for this:
https://github.com/oazapfts/oazapfts/issues/486
