### ISSUE TITLE
RTK 2: Cannot use `create.asyncThunk` in the built-in `createSlice`

### ISSUE THREAD

**Issue by einarq** [reduxjs/redux-toolkit#3958]
When running in tests in karma+jasmine I get this error.

When would this error be thrown?

Error: Cannot use `create.asyncThunk` in the built-in `createSlice`. Use `buildCreateSlice({ creators: { asyncThunk: asyncThunkCreator } })` to create a customised version of `createSlice`.
      at handleThunkCaseReducerDefinition (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/commons.js:795773:11)
      at C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/commons.js:795602:9
      at Array.forEach (<anonymous>)
      at createSlice2 (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/commons.js:795594:18)
      at ./www/js/app/modules/deployment/reducers/launch-options.ts (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/commons.js:234392:79)
      at __webpack_require__ (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/runtime.js:23:42)
      at ./www/js/app/reducers/index.ts (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/commons.js:493062:22)
      at __webpack_require__ (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/runtime.js:23:42)
      at ./www/js/app/components/duplicate-delete-survey.jsx (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/commons.js:154814:17)
      at __webpack_require__ (C:/Users/einarq/AppData/Local/Temp/_karma_webpack_507790/runtime.js:23:42)

**Comment by EskiMojo14** [comment]
To avoid createSlice including createAsyncThunk's bundle size by default, you need to [set up a version of createSlice](https://redux-toolkit.js.org/api/createSlice#createasyncthunk) that supports create.asyncThunk.
