### ISSUE TITLE
Testing RTK Query Leads to "test was not wrapped in act"

### ISSUE THREAD

**Issue by jd-carroll** [reduxjs/redux-toolkit#4033]
I have a pretty loose handle as to what is going on, but here is the basic situation:

I am using NextJS with @reduxjs/toolkit v1.9.7 and Jest as my test runner. My component library is Radix-UI and while my tests pass, I receive `When testing, code that causes React state updates should be wrapped into act(...)` errors (full trace below).

The DOM stack trace points to my component library, but I think that is simply the first place where a state change is called during render. I'm actually thinking that the issue is related to RTK Query (maybe a configuration issue?).

If I debug the test case, I see my API call triggered (`'api/userAction/pending'`) and everything updates without issue.

The errors occur when the `'api/userAction/fulfilled'` event is fired and the update is being dispatched to all listeners. During this process a react store change handler forces a re-render of my component.  Here is the exact code from react-dom:
```typescript
function subscribeToStore(fiber, inst, subscribe) {
  var handleStoreChange = function () {
    // The store changed. Check if the snapshot changed since the last time we
    // read from the store.
    if (checkIfSnapshotChanged(inst)) {
      // Force a re-render.
      forceStoreRerender(fiber);
    }
  }; // Subscribe to the store and return a clean-up function.


  return subscribe(handleStoreChange);
}
```

But this, obviously(?), isn't wrapped in an `act(...)`.

So first question, is this a bug or configuration issue?

**I'm going to assume this is a configuration issue. How do I wrap the `fullfilled` event handling of RTK Query in an `act(...)` handler?**

To be clear, I am totally lost on this issue. So please take any descriptions / assessments with a grain of salt.

I would also love to provide a nice reproducible test case, but I am so lost I'm not really sure where to start. Additionally, my tests do pass; but something doesn't leave me with a nice feeling.

Last thought: I am using RTK Query react hooks, so in the submit handler of my form I call the mutation trigger and then have two separate `useEffect` hooks which monitor for the success and failure cases respectively. ... 

**Is that the issue? Would I be better off using a try/catch & await in the submit handler?**

<details>

  <summary>Example code triggering the `userAction`</summary>

```typescript

const getInitialValues = (existing?: Values): Values => ({
  // ... set the initial values
});

// Note: The submit handler is passed to a Formik component
export function useStep1FormControls({ plan, defaultNickname }: Step1FormControlsProps): FormControls {
  const { session } = useSession();

  const [isFormComplete, setFormComplete] = React.useState(false);
  const [userAction, { isLoading, isSuccess, error, data, originalArgs }] =
    useUserActionMutation();

  const [validationError, setErrorReason] = React.useState<string | undefined>(undefined);

  React.useEffect(() => {
    if (!isSuccess || !data || !originalArgs) {
      return;
    }
    setFormComplete(true);

    // ... handle the success result
  }, [isSuccess, originalArgs, data]);

  React.useEffect(() => {
    if (!error) {
      return;
    }

    switch (error.code) {
      // ... handle the error result
    }
  }, [error]);

  const handleSubmit: (
    account: Values,
    formikHelpers: FormikHelpers<Values>
  ) => void = React.useCallback(
    (account, { setSubmitting }) => {
      if (isLoading) {
        return;
      }

      void userAction({
        account,
        sessionUuid: session.sessionUuid
      })
        .unwrap()
        .catch(() => {
          setSubmitting(false);
        });
    },
    [isLoading, userAction, session]
  );

  const initial = React.useMemo(() => getInitialValues(originalArgs?.account), [originalArgs?.account]);

  return { isFormComplete, initial, plan, validationError, onSubmit: handleSubmit };
}
```

</details>

<details>

<summary>Stacktrace of error</summary>

```
  console.error
    Warning: An update to Checkbox inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/react-checkbox/dist/packages/react/checkbox/src/Checkbox.tsx:45:7
        at ... <dom-tree>

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (../../node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at scheduleUpdateOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at setButton (../../node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at ref (../../node_modules/@radix-ui/react-checkbox/dist/packages/react/checkbox/src/Checkbox.tsx:56:66)
      at setRef (../../node_modules/@radix-ui/react-compose-refs/dist/packages/react/compose-refs/src/composeRefs.tsx:11:5)
      at forEach (../../node_modules/@radix-ui/react-compose-refs/dist/packages/react/compose-refs/src/composeRefs.tsx:22:45)
          at Array.forEach (<anonymous>)
      at ../../node_modules/@radix-ui/react-compose-refs/dist/packages/react/compose-refs/src/composeRefs.tsx:22:28
      at commitAttachRef (../../node_modules/react-dom/cjs/react-dom.development.js:23650:18)
      at commitLayoutEffectOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:23503:9)
      at commitLayoutMountEffects_complete (../../node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (../../node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (../../node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (../../node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (../../node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (../../node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at workLoop (../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:266:34)
      at flushWork (../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:239:14)
      at performWorkUntilDeadline (../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:533:21)
      at Timeout.task [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)

```
</details>

Any help / insights greatly appreciated :heart:

**Comment by markerikson** [comment]
Can you show what the test code looks like?

You may need something like this:

```ts
await act(async () => {
  await screen.getByText("Click Me").click()
})
```

(You might also want to glance at our own RTK Query test files, since we definitely have tests that do async work.)

**Comment by jd-carroll** [comment]
I've copied the exact code of the test below.  I've also definitely looked at the RTK Query test files, but I'll look through again to see if I'm missing something.

As for the `await act(async ...`, I've definitely tried varying combinations of:

```typescript
    await act(async () => {
      render(...)
    });
```

```typescript
    await act(async () => {
      await events.click(screen.getByTestId('newsletter'));
      await events.click(screen.getByTestId('submit'));
    });
```

```typescript
    await act(async () => {
      await events.click(screen.getByTestId('newsletter'));
    });
    await act(async () => {
      await events.click(screen.getByTestId('submit'));
    });
```

But I still receive errors along the lines of:

```
  console.error
    Warning: The current testing environment is not configured to support act(...)

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at isConcurrentActEnvironment (../../node_modules/react-dom/cjs/react-dom.development.js:25260:7)
```

Or the same `Warning: An update to Checkbox inside a test was not wrapped in act(...).`


```typescript
describe('Features | Sign-Up | Components | Step 1 - Account Details', () => {
  it.only('should pass all the data', async () => {
    // Setup test data
    const session = TestSignUpSession.New();
    const user = TestUserAccount.Brad();
    const organization = TestOrganization.Family();

    // Custom MSW handlers
    const createSessionHandler = InternalSignUpApiV1Test.endpoints.createSession({ data: { session } });
    const reserveUserAccountHandler = InternalSignUpApiV1Test.endpoints
      .reserveUserAccount({
        data: { status: SignUpSessionStatus.Initialized, userAccountUuid: user.userAccountUuid },
        params: { sessionUuid: session.sessionUuid }
      })
      .capture();

    // Initialize the MSW server api
    server.use(createSessionHandler, reserveUserAccountHandler);

    const events = userEvent.setup();

    render(
      <SignUpSessionProvider>
        <Step1AccountDetails
          defaultNickname="Our family"
          plan={OrganizationType.Family}
          Links={{
            DashboardSignIn: 'sign-in',
            PrivacyPolicy: 'privacy-policy',
            SignUpStep2: 'step-2',
            TermsOfService: 'terms-of-service'
          }}
        />
      </SignUpSessionProvider>
    );

    await events.type(screen.getByTestId('name'), user.name);
    await events.type(screen.getByTestId('email'), user.email);
    await events.type(screen.getByTestId('nickname'), organization.nickname);
    await events.click(screen.getByTestId('newsletter'));

    await events.click(screen.getByTestId('submit'));

    // Custom developed hook to wait for all pending MSW requests to complete
    // Note: I think if the issue of "should be wrapped into act(...)" is fixed, this can be removed
    await Promise.allSettled(server.allActiveRequests().map(({ promise }) => promise));

    const expected: ApiV1SignUpReserveUserAccountRequest = {
      account: {
        email: user.email,
        name: user.name,
        nickname: organization.nickname,
        newsletter: false,
        plan: OrganizationType.Family,
        language: 'en'
      }
    };

    // assert that the server received the expected request
    expect(reserveUserAccountHandler.getRequests().length).toEqual(1);
    expect(reserveUserAccountHandler.getRequest().body).toEqual(expected);
  });
});

```

**Comment by jd-carroll** [comment]
Just changed that submit handler to remove both use effect hooks and instead have all the logic in the submit handler with an `await` and I still see the same errors

**Comment by phryneas** [comment]
The problem is not the `act` around the `click`. The api response comes in later after that, triggering another render that is not wrapped in `act` (our code cannot contain extra test code). 

So the code that is waiting for an UI change has to be wrapped in `act`.

Either something like
```js
await act(() => Promise.allSettled(server.allActiveRequests().map(({ promise }) => promise)))
```
or something like
```js
waitFor(() => expect(reserveUserAccountHandler.getRequests().length).toEqual(1))
```
(`waitFor` should do the `act`-wrapping itself)

**Comment by jd-carroll** [comment]
@phryneas - THANK YOU! I think I came up with a solution that's actually pretty cool. 
(Then again, it might be crap... The last couple of months of learning RTK and React generally have been pretty humbling :joy:)

Your second suggestion got me thinking about a middleware resolver to add to the store. So here is the meat of the solution:
```typescript
const reservedResponse = createMiddlewareResolver({
  predicate: (action) => {
    return InternalSignUpApiV1.endpoints.reserveUserAccount.matchFulfilled(action);
  }
});
```

I've copied the full test case below. 

I'm pumped and really appreciate the support both of you provided. Happy to answer any questions about the implementation (if on the off chance you had any).

Thanks again

<details>

<summary>Finalized Test Case</summary>

```typescript
describe('Features | Sign-Up | Components | Step 1 - Account Details', () => {
  it.only('should pass all the data', async () => {
    // Setup test data
    const session = TestSignUpSession.New();
    const user = TestUserAccount.Joseph();
    const organization = TestOrganization.Family();

    // Custom MSW handlers
    const createSessionHandler = InternalSignUpApiV1Test.endpoints.createSession({ data: { session } });
    const reserveUserAccountHandler = InternalSignUpApiV1Test.endpoints
      .reserveUserAccount({
        data: { status: SignUpSessionStatus.Initialized, userAccountUuid: user.userAccountUuid },
        params: { sessionUuid: session.sessionUuid }
      })
      .capture();

    // Initialize the MSW server api
    server.use(createSessionHandler, reserveUserAccountHandler);

    const events = userEvent.setup();

    // Enables testing whether or not the page automatically advances to the next step
    const resolveOnStep2 = createRouterResolver(({ resolve, reject }, name: string, href?: string) => {
      if (name === 'push' && typeof href === 'string' && href.startsWith('step-2?hash=')) {
        resolve();
      } else {
        reject(`Unexpected router call: ${name}(${href})`);
      }
    });

    // Enables waiting for reserveUserAccount to complete
    const reservedResponse = createMiddlewareResolver({
      predicate: (action) => {
        return InternalSignUpApiV1.endpoints.reserveUserAccount.matchFulfilled(action);
      }
    });

    renderTestableComponent(
      () => (
        <SignUpSessionProvider>
          <Step1AccountDetails
            defaultNickname="Our family"
            plan={OrganizationType.Family}
            Links={{
              DashboardSignIn: 'sign-in',
              PrivacyPolicy: 'privacy-policy',
              SignUpStep2: 'step-2',
              TermsOfService: 'terms-of-service'
            }}
          />
        </SignUpSessionProvider>
      ),
      {
        config: {
          next: {
            router: { action: { push: resolveOnStep2.resolver } }
          },
          store: {
            middleware: [reservedResponse.middleware]
          }
        }
      }
    );

    await events.type(screen.getByTestId('name'), user.name);
    await events.type(screen.getByTestId('email'), user.email);
    await events.type(screen.getByTestId('nickname'), organization.nickname);
    await events.click(screen.getByTestId('newsletter'));

    await events.click(screen.getByTestId('submit'));

    // Wait for the api and router update to complete (fails after 1s)
    await waitFor(() => Promise.allSettled([reservedResponse.promise, resolveOnStep2.promise]));

    const expected: ApiV1SignUpReserveUserAccountRequest = {
      account: {
        email: user.email,
        name: user.name,
        nickname: organization.nickname,
        newsletter: false,
        plan: OrganizationType.Family,
        language: 'en'
      }
    };

    //assert on the times called and arguments given to fetch
    expect(reserveUserAccountHandler.getRequests().length).toEqual(1);
    expect(reserveUserAccountHandler.getRequest().body).toEqual(expected);
    // TODO: assert on the router call
    // TODO: assert on the api response
  });
});
```

</details>
