### ISSUE TITLE
Codegen OpenAPI: negative numbers cause error

### ISSUE THREAD

**Issue by Innders** [reduxjs/redux-toolkit#4455]
When I try to run `npx @rtk-query/codegen-openapi openapi-config.ts` I get the error:

```
Error: Debug Failure. False expression: Negative numbers should be created in combination with createPrefixUnaryExpression
    at Object.createNumericLiteral (/path/to/project/node_modules/typescript/lib/typescript.js:21094:13)
    at createLiteral (/path/to/project/node_modules/oazapfts/src/codegen/tscodegen.ts:42:22)
    at /path/to/project/node_modules/oazapfts/src/codegen/tscodegen.ts:50:39
    at Array.map (<anonymous>)
    at Object.createEnumTypeNode (/path/to/project/node_modules/oazapfts/src/codegen/tscodegen.ts:47:24)
    at ApiGenerator.getBaseTypeFromSchema (/path/to/project/node_modules/oazapfts/src/codegen/generate.ts:689:14)
    at ApiGenerator.getTypeFromSchema (/path/to/project/node_modules/oazapfts/src/codegen/generate.ts:563:23)
    at ApiGenerator.getRefAlias (/path/to/project/node_modules/oazapfts/src/codegen/generate.ts:432:25)
    at ApiGenerator.getBaseTypeFromSchema (/path/to/project/node_modules/oazapfts/src/codegen/generate.ts:580:19)
    at ApiGenerator.getTypeFromSchema (/path/to/project/node_modules/oazapfts/src/codegen/generate.ts:563:23)
 ```

openapi-config.ts

```
const config: ConfigFile = {
  schemaFile: 'https://ayon.dev/openapi.json',
  apiFile: './src/services/ayon.ts',
  apiImport: 'RestAPI',
  outputFile: './src/services/ayonRestTypes.ts',
  exportName: 'ayonRestApi',
}
```

If I exclude a specific endpoint `filterEndpoints: [/^(?!.*sitesync).*$/i]` then I don't get this error and everything is great.

The endpoint has a negative enum value (-1) and I believe this is the cause of the error.
![image](https://github.com/reduxjs/redux-toolkit/assets/49156310/534fb4bb-0c8e-4fa2-84ce-d02f759ed23b)

I found a similar issue report for this negative number error here (not sure how related it is): https://github.com/hey-api/openapi-ts/issues/466#issuecomment-2069303641

It doesn't look like openapi-ts is being used but maybe this is still helpful.

**Comment by Innders** [comment]
Oh sorry I missed the PR, thanks! At least this issue might come up in a google search now for someone like me....

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.

**Comment by Innders** [comment]
> Please try it out and let us know if it works.

I can confirm that this fixes the issue! Thanks 💯 

![image](https://github.com/user-attachments/assets/e12088dc-45de-459c-86f0-640582f52a3d)
