### ISSUE TITLE
@rtk-query/codegen-openapi: Invalid or unexpected token

### ISSUE THREAD

**Issue by vladinko0** [reduxjs/redux-toolkit#4597]
"@rtk-query/codegen-openapi": "^1.2.0",

In my project I am using this code:

```
export const clientConfig: TClient = {
  clientLogoPath: require('./src/assets/images/appLogo.png')
}
```

It causes this error:
```
/Users/user/Projekty/proj/src/assets/images/appLogo.png:1
�PNG


SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/Users/user/Projekty/proj/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/user/Projekty/proj/app.config.ts:24:19)
```

**Comment by markerikson** [comment]
Your build tool is returning the actual bytes of the PNG file, instead of some kind of path string.
