### ISSUE TITLE
Support for react-native

### ISSUE THREAD

**Issue by ShekharD175** [reduxjs/redux-toolkit#523]
Getting error while using it with react-native, 

```
CXX(target) Release/obj.target/fse/fsevents.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../fsevents.cc:72:
../src/thread.cc:36:25: error: unknown type name 'ConstFSEventStreamRef'
void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags ...
                        ^
../src/thread.cc:36:108: error: unknown type name 'FSEventStreamEventFlags'
void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags ...
                                                                                                           ^
../src/thread.cc:36:152: error: unknown type name 'FSEventStreamEventId'
  ...stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags eventFlags[], const FSEventStreamEventId event...
                                                                                                              ^
../src/thread.cc:54:3: error: unknown type name 'FSEventStreamContext'
  FSEventStreamContext context = { 0, ctx, NULL, NULL, NULL };
  ^
../src/thread.cc:56:3: error: unknown type name 'FSEventStreamRef'
  FSEventStreamRef stream = FSEventStreamCreate(NULL, &HandleStreamEvents, &context, fse->paths, kFSEventStreamEventIdSinceNow, (CF...
  ^
../src/thread.cc:56:98: error: use of undeclared identifier 'kFSEventStreamEventIdSinceNow'
  FSEventStreamRef stream = FSEventStreamCreate(NULL, &HandleStreamEvents, &context, fse->paths, kFSEventStreamEventIdSinceNow, (CF...
                                                                                                 ^
6 errors generated.
```

**Comment by ShekharD175** [comment]
getting above errors while "npm install" or "yarn install"

**Comment by phryneas** [comment]
This is a C++ error - there is nothing in that error message that would make me believe even remotely that it has any correlation to RTK, which is written purely in JavaScript. 
Could you please elaborate how you come to that conclusion?

**Comment by markerikson** [comment]
Yep, this has nothing to do with RTK.

**Comment by ShekharD175** [comment]
@phryneas I just created one react-native application and tried to add RTK in that, so while installing RTK I got above errors, and I am not able to run my React-Native application

**Comment by ShekharD175** [comment]
After running the react-native app, getting the following error on "npm start"

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/{path_to_Project}/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:135:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Todo@0.0.1 start: `react-native start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Todo@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/****/.npm/_logs/2020-04-26T04_26_19_403Z-debug.log
```

I have created another demo app with react-native and tried to run it, it works..!! Getting these errors after installation of RTK.

**Comment by ShekharD175** [comment]
To. resolve above error I updated watchmen also, But if this is related to the watchmen then I think the second application should give me the same error but it's working fine.

**Comment by markerikson** [comment]
Yeah, this truly has nothing to do with RTK or Redux at all.
